//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APILogic.DmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PushData", Namespace="http://schemas.datacontract.org/2004/07/DmsV2.Models.Responses")]
    [System.SerializableAttribute()]
    public partial class PushData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationExternalTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationExternalToken {
            get {
                return this.ApplicationExternalTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationExternalTokenField, value) != true)) {
                    this.ApplicationExternalTokenField = value;
                    this.RaisePropertyChanged("ApplicationExternalToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalToken {
            get {
                return this.ExternalTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalTokenField, value) != true)) {
                    this.ExternalTokenField = value;
                    this.RaisePropertyChanged("ExternalToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Udid {
            get {
                return this.UdidField;
            }
            set {
                if ((object.ReferenceEquals(this.UdidField, value) != true)) {
                    this.UdidField = value;
                    this.RaisePropertyChanged("Udid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetPushData", Namespace="http://schemas.datacontract.org/2004/07/DmsV2.Models.Responses")]
    [System.SerializableAttribute()]
    public partial class SetPushData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalToken {
            get {
                return this.ExternalTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalTokenField, value) != true)) {
                    this.ExternalTokenField = value;
                    this.RaisePropertyChanged("ExternalToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Udid {
            get {
                return this.UdidField;
            }
            set {
                if ((object.ReferenceEquals(this.UdidField, value) != true)) {
                    this.UdidField = value;
                    this.RaisePropertyChanged("Udid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DmsService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPushData", ReplyAction="http://tempuri.org/IService/GetPushDataResponse")]
        APILogic.DmsService.PushData[] GetPushData(int groupId, string[] udids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPushData", ReplyAction="http://tempuri.org/IService/GetPushDataResponse")]
        System.Threading.Tasks.Task<APILogic.DmsService.PushData[]> GetPushDataAsync(int groupId, string[] udids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetPushData", ReplyAction="http://tempuri.org/IService/SetPushDataResponse")]
        bool SetPushData(int groupId, APILogic.DmsService.SetPushData pushData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetPushData", ReplyAction="http://tempuri.org/IService/SetPushDataResponse")]
        System.Threading.Tasks.Task<bool> SetPushDataAsync(int groupId, APILogic.DmsService.SetPushData pushData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : APILogic.DmsService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<APILogic.DmsService.IService>, APILogic.DmsService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public APILogic.DmsService.PushData[] GetPushData(int groupId, string[] udids) {
            return base.Channel.GetPushData(groupId, udids);
        }
        
        public System.Threading.Tasks.Task<APILogic.DmsService.PushData[]> GetPushDataAsync(int groupId, string[] udids) {
            return base.Channel.GetPushDataAsync(groupId, udids);
        }
        
        public bool SetPushData(int groupId, APILogic.DmsService.SetPushData pushData) {
            return base.Channel.SetPushData(groupId, pushData);
        }
        
        public System.Threading.Tasks.Task<bool> SetPushDataAsync(int groupId, APILogic.DmsService.SetPushData pushData) {
            return base.Channel.SetPushDataAsync(groupId, pushData);
        }
    }
}
