//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace M1BL.MobileOneBusinessFascadeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceInterfaceSoap", Namespace="http://m1.com.sg/ServiceInterface")]
    public partial class ServiceInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenticationSoapHeader authenticationSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private System.Threading.SendOrPostCallback XMLtestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteAsObjectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceInterface() {
            this.Url = global::M1BL.Properties.Settings.Default.M1BL_MobileOneBusinessFascadeService_ServiceInterface;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationSoapHeader AuthenticationSoapHeaderValue {
            get {
                return this.authenticationSoapHeaderValueField;
            }
            set {
                this.authenticationSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        public event XMLtestCompletedEventHandler XMLtestCompleted;
        
        /// <remarks/>
        public event ExecuteAsObjectCompletedEventHandler ExecuteAsObjectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://m1.com.sg/ServiceInterface/Execute", RequestNamespace="http://m1.com.sg/ServiceInterface", ResponseNamespace="http://m1.com.sg/ServiceInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandardStringArrayResult Execute(string inputXML, string sChannelId, string sUserId, bool onErrorContinue) {
            object[] results = this.Invoke("Execute", new object[] {
                        inputXML,
                        sChannelId,
                        sUserId,
                        onErrorContinue});
            return ((StandardStringArrayResult)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(string inputXML, string sChannelId, string sUserId, bool onErrorContinue) {
            this.ExecuteAsync(inputXML, sChannelId, sUserId, onErrorContinue, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(string inputXML, string sChannelId, string sUserId, bool onErrorContinue, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        inputXML,
                        sChannelId,
                        sUserId,
                        onErrorContinue}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://m1.com.sg/ServiceInterface/XMLtest", RequestNamespace="http://m1.com.sg/ServiceInterface", ResponseNamespace="http://m1.com.sg/ServiceInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XMLtest() {
            object[] results = this.Invoke("XMLtest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XMLtestAsync() {
            this.XMLtestAsync(null);
        }
        
        /// <remarks/>
        public void XMLtestAsync(object userState) {
            if ((this.XMLtestOperationCompleted == null)) {
                this.XMLtestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXMLtestOperationCompleted);
            }
            this.InvokeAsync("XMLtest", new object[0], this.XMLtestOperationCompleted, userState);
        }
        
        private void OnXMLtestOperationCompleted(object arg) {
            if ((this.XMLtestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XMLtestCompleted(this, new XMLtestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://m1.com.sg/ServiceInterface/ExecuteAsObject", RequestNamespace="http://m1.com.sg/ServiceInterface", ResponseNamespace="http://m1.com.sg/ServiceInterface", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandardObjectArrayResult ExecuteAsObject(object inputObject, string sChannelId, string sUserId, bool onErrorContinue) {
            object[] results = this.Invoke("ExecuteAsObject", new object[] {
                        inputObject,
                        sChannelId,
                        sUserId,
                        onErrorContinue});
            return ((StandardObjectArrayResult)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsObjectAsync(object inputObject, string sChannelId, string sUserId, bool onErrorContinue) {
            this.ExecuteAsObjectAsync(inputObject, sChannelId, sUserId, onErrorContinue, null);
        }
        
        /// <remarks/>
        public void ExecuteAsObjectAsync(object inputObject, string sChannelId, string sUserId, bool onErrorContinue, object userState) {
            if ((this.ExecuteAsObjectOperationCompleted == null)) {
                this.ExecuteAsObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteAsObjectOperationCompleted);
            }
            this.InvokeAsync("ExecuteAsObject", new object[] {
                        inputObject,
                        sChannelId,
                        sUserId,
                        onErrorContinue}, this.ExecuteAsObjectOperationCompleted, userState);
        }
        
        private void OnExecuteAsObjectOperationCompleted(object arg) {
            if ((this.ExecuteAsObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteAsObjectCompleted(this, new ExecuteAsObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://m1.com.sg/ServiceInterface")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://m1.com.sg/ServiceInterface", IsNullable=false)]
    public partial class AuthenticationSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string credentialField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Credential {
            get {
                return this.credentialField;
            }
            set {
                this.credentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://m1.com.sg/ServiceInterface")]
    public partial class StandardObjectArrayResult {
        
        private ExceptionResult webServiceResultField;
        
        private object[] returnField;
        
        /// <remarks/>
        public ExceptionResult WebServiceResult {
            get {
                return this.webServiceResultField;
            }
            set {
                this.webServiceResultField = value;
            }
        }
        
        /// <remarks/>
        public object[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://m1.com.sg/ServiceInterface")]
    public partial class ExceptionResult {
        
        private int errorCodeField;
        
        private string exceptionsField;
        
        private string errorMessagesField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                this.errorMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://m1.com.sg/ServiceInterface")]
    public partial class StandardStringArrayResult {
        
        private ExceptionResult webServiceResultField;
        
        private string[] returnField;
        
        /// <remarks/>
        public ExceptionResult WebServiceResult {
            get {
                return this.webServiceResultField;
            }
            set {
                this.webServiceResultField = value;
            }
        }
        
        /// <remarks/>
        public string[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandardStringArrayResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandardStringArrayResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void XMLtestCompletedEventHandler(object sender, XMLtestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XMLtestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XMLtestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ExecuteAsObjectCompletedEventHandler(object sender, ExecuteAsObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteAsObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteAsObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandardObjectArrayResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandardObjectArrayResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591