//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdapterControllers.CdnAdapter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValue", Namespace="http://schemas.datacontract.org/2004/07/PGAdapterCommon.Models")]
    [System.SerializableAttribute()]
    public partial class KeyValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdapterStatus", Namespace="http://schemas.datacontract.org/2004/07/PGAdapterCommon.Models")]
    [System.SerializableAttribute()]
    public partial class AdapterStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkResponse", Namespace="http://schemas.datacontract.org/2004/07/CDNAdapter.Models")]
    [System.SerializableAttribute()]
    public partial class LinkResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.CdnAdapter.Link LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.CdnAdapter.AdapterStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.CdnAdapter.Link Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.CdnAdapter.AdapterStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Link", Namespace="http://schemas.datacontract.org/2004/07/CDNAdapter.Models")]
    [System.SerializableAttribute()]
    public partial class Link : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderStatusMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderStatusCode {
            get {
                return this.ProviderStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderStatusCodeField, value) != true)) {
                    this.ProviderStatusCodeField = value;
                    this.RaisePropertyChanged("ProviderStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderStatusMessage {
            get {
                return this.ProviderStatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderStatusMessageField, value) != true)) {
                    this.ProviderStatusMessageField = value;
                    this.RaisePropertyChanged("ProviderStatusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CdnAdapter.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetConfiguration", ReplyAction="http://tempuri.org/IService/SetConfigurationResponse")]
        AdapterControllers.CdnAdapter.AdapterStatus SetConfiguration(int adapterId, AdapterControllers.CdnAdapter.KeyValue[] settings, int partnerId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetConfiguration", ReplyAction="http://tempuri.org/IService/SetConfigurationResponse")]
        System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.AdapterStatus> SetConfigurationAsync(int adapterId, AdapterControllers.CdnAdapter.KeyValue[] settings, int partnerId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetVodLink", ReplyAction="http://tempuri.org/IService/GetVodLinkResponse")]
        AdapterControllers.CdnAdapter.LinkResponse GetVodLink(int adapterId, string userId, string url, string fileType, int assetId, int contentId, string ip, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetVodLink", ReplyAction="http://tempuri.org/IService/GetVodLinkResponse")]
        System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.LinkResponse> GetVodLinkAsync(int adapterId, string userId, string url, string fileType, int assetId, int contentId, string ip, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRecordingLink", ReplyAction="http://tempuri.org/IService/GetRecordingLinkResponse")]
        AdapterControllers.CdnAdapter.LinkResponse GetRecordingLink(int adapterId, string userId, string url, string fileType, string recordingId, string ip, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRecordingLink", ReplyAction="http://tempuri.org/IService/GetRecordingLinkResponse")]
        System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.LinkResponse> GetRecordingLinkAsync(int adapterId, string userId, string url, string fileType, string recordingId, string ip, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEpgLink", ReplyAction="http://tempuri.org/IService/GetEpgLinkResponse")]
        AdapterControllers.CdnAdapter.LinkResponse GetEpgLink(int adapterId, string userId, string url, string fileType, int programId, int assetId, int contentId, long startTimeSeconds, int actionType, string ip, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEpgLink", ReplyAction="http://tempuri.org/IService/GetEpgLinkResponse")]
        System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.LinkResponse> GetEpgLinkAsync(int adapterId, string userId, string url, string fileType, int programId, int assetId, int contentId, long startTimeSeconds, int actionType, string ip, long timeStamp, string signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : AdapterControllers.CdnAdapter.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<AdapterControllers.CdnAdapter.IService>, AdapterControllers.CdnAdapter.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdapterControllers.CdnAdapter.AdapterStatus SetConfiguration(int adapterId, AdapterControllers.CdnAdapter.KeyValue[] settings, int partnerId, long timeStamp, string signature) {
            return base.Channel.SetConfiguration(adapterId, settings, partnerId, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.AdapterStatus> SetConfigurationAsync(int adapterId, AdapterControllers.CdnAdapter.KeyValue[] settings, int partnerId, long timeStamp, string signature) {
            return base.Channel.SetConfigurationAsync(adapterId, settings, partnerId, timeStamp, signature);
        }
        
        public AdapterControllers.CdnAdapter.LinkResponse GetVodLink(int adapterId, string userId, string url, string fileType, int assetId, int contentId, string ip, long timeStamp, string signature) {
            return base.Channel.GetVodLink(adapterId, userId, url, fileType, assetId, contentId, ip, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.LinkResponse> GetVodLinkAsync(int adapterId, string userId, string url, string fileType, int assetId, int contentId, string ip, long timeStamp, string signature) {
            return base.Channel.GetVodLinkAsync(adapterId, userId, url, fileType, assetId, contentId, ip, timeStamp, signature);
        }
        
        public AdapterControllers.CdnAdapter.LinkResponse GetRecordingLink(int adapterId, string userId, string url, string fileType, string recordingId, string ip, long timeStamp, string signature) {
            return base.Channel.GetRecordingLink(adapterId, userId, url, fileType, recordingId, ip, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.LinkResponse> GetRecordingLinkAsync(int adapterId, string userId, string url, string fileType, string recordingId, string ip, long timeStamp, string signature) {
            return base.Channel.GetRecordingLinkAsync(adapterId, userId, url, fileType, recordingId, ip, timeStamp, signature);
        }
        
        public AdapterControllers.CdnAdapter.LinkResponse GetEpgLink(int adapterId, string userId, string url, string fileType, int programId, int assetId, int contentId, long startTimeSeconds, int actionType, string ip, long timeStamp, string signature) {
            return base.Channel.GetEpgLink(adapterId, userId, url, fileType, programId, assetId, contentId, startTimeSeconds, actionType, ip, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.CdnAdapter.LinkResponse> GetEpgLinkAsync(int adapterId, string userId, string url, string fileType, int programId, int assetId, int contentId, long startTimeSeconds, int actionType, string ip, long timeStamp, string signature) {
            return base.Channel.GetEpgLinkAsync(adapterId, userId, url, fileType, programId, assetId, contentId, startTimeSeconds, actionType, ip, timeStamp, signature);
        }
    }
}
