//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace TVPApiTests.SocialService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SocialServiceSoap", Namespace="http://platform-us.tvinci.com/tvpapi/ws")]
    public partial class SocialService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllFriendsWatchedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFriendsWatchedByMediaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersLikedMediaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserFriendsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FBConfigOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SocialService() {
            this.Url = global::TVPApiTests.Properties.Settings.Default.TVPApiTests_SocialService_SocialService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllFriendsWatchedCompletedEventHandler GetAllFriendsWatchedCompleted;
        
        /// <remarks/>
        public event GetFriendsWatchedByMediaCompletedEventHandler GetFriendsWatchedByMediaCompleted;
        
        /// <remarks/>
        public event GetUsersLikedMediaCompletedEventHandler GetUsersLikedMediaCompleted;
        
        /// <remarks/>
        public event GetUserFriendsCompletedEventHandler GetUserFriendsCompleted;
        
        /// <remarks/>
        public event FBConfigCompletedEventHandler FBConfigCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://platform-us.tvinci.com/tvpapi/ws/GetAllFriendsWatched", RequestNamespace="http://platform-us.tvinci.com/tvpapi/ws", ResponseNamespace="http://platform-us.tvinci.com/tvpapi/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FriendWatchedObject[] GetAllFriendsWatched(InitializationObject initObj, int maxResult) {
            object[] results = this.Invoke("GetAllFriendsWatched", new object[] {
                        initObj,
                        maxResult});
            return ((FriendWatchedObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllFriendsWatchedAsync(InitializationObject initObj, int maxResult) {
            this.GetAllFriendsWatchedAsync(initObj, maxResult, null);
        }
        
        /// <remarks/>
        public void GetAllFriendsWatchedAsync(InitializationObject initObj, int maxResult, object userState) {
            if ((this.GetAllFriendsWatchedOperationCompleted == null)) {
                this.GetAllFriendsWatchedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllFriendsWatchedOperationCompleted);
            }
            this.InvokeAsync("GetAllFriendsWatched", new object[] {
                        initObj,
                        maxResult}, this.GetAllFriendsWatchedOperationCompleted, userState);
        }
        
        private void OnGetAllFriendsWatchedOperationCompleted(object arg) {
            if ((this.GetAllFriendsWatchedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllFriendsWatchedCompleted(this, new GetAllFriendsWatchedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://platform-us.tvinci.com/tvpapi/ws/GetFriendsWatchedByMedia", RequestNamespace="http://platform-us.tvinci.com/tvpapi/ws", ResponseNamespace="http://platform-us.tvinci.com/tvpapi/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FriendWatchedObject[] GetFriendsWatchedByMedia(InitializationObject initObj, int mediaId) {
            object[] results = this.Invoke("GetFriendsWatchedByMedia", new object[] {
                        initObj,
                        mediaId});
            return ((FriendWatchedObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFriendsWatchedByMediaAsync(InitializationObject initObj, int mediaId) {
            this.GetFriendsWatchedByMediaAsync(initObj, mediaId, null);
        }
        
        /// <remarks/>
        public void GetFriendsWatchedByMediaAsync(InitializationObject initObj, int mediaId, object userState) {
            if ((this.GetFriendsWatchedByMediaOperationCompleted == null)) {
                this.GetFriendsWatchedByMediaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFriendsWatchedByMediaOperationCompleted);
            }
            this.InvokeAsync("GetFriendsWatchedByMedia", new object[] {
                        initObj,
                        mediaId}, this.GetFriendsWatchedByMediaOperationCompleted, userState);
        }
        
        private void OnGetFriendsWatchedByMediaOperationCompleted(object arg) {
            if ((this.GetFriendsWatchedByMediaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFriendsWatchedByMediaCompleted(this, new GetFriendsWatchedByMediaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://platform-us.tvinci.com/tvpapi/ws/GetUsersLikedMedia", RequestNamespace="http://platform-us.tvinci.com/tvpapi/ws", ResponseNamespace="http://platform-us.tvinci.com/tvpapi/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetUsersLikedMedia(InitializationObject initObj, int mediaID, bool onlyFriends, int startIndex, int pageSize) {
            object[] results = this.Invoke("GetUsersLikedMedia", new object[] {
                        initObj,
                        mediaID,
                        onlyFriends,
                        startIndex,
                        pageSize});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersLikedMediaAsync(InitializationObject initObj, int mediaID, bool onlyFriends, int startIndex, int pageSize) {
            this.GetUsersLikedMediaAsync(initObj, mediaID, onlyFriends, startIndex, pageSize, null);
        }
        
        /// <remarks/>
        public void GetUsersLikedMediaAsync(InitializationObject initObj, int mediaID, bool onlyFriends, int startIndex, int pageSize, object userState) {
            if ((this.GetUsersLikedMediaOperationCompleted == null)) {
                this.GetUsersLikedMediaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersLikedMediaOperationCompleted);
            }
            this.InvokeAsync("GetUsersLikedMedia", new object[] {
                        initObj,
                        mediaID,
                        onlyFriends,
                        startIndex,
                        pageSize}, this.GetUsersLikedMediaOperationCompleted, userState);
        }
        
        private void OnGetUsersLikedMediaOperationCompleted(object arg) {
            if ((this.GetUsersLikedMediaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersLikedMediaCompleted(this, new GetUsersLikedMediaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://platform-us.tvinci.com/tvpapi/ws/GetUserFriends", RequestNamespace="http://platform-us.tvinci.com/tvpapi/ws", ResponseNamespace="http://platform-us.tvinci.com/tvpapi/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetUserFriends(InitializationObject initObj) {
            object[] results = this.Invoke("GetUserFriends", new object[] {
                        initObj});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUserFriendsAsync(InitializationObject initObj) {
            this.GetUserFriendsAsync(initObj, null);
        }
        
        /// <remarks/>
        public void GetUserFriendsAsync(InitializationObject initObj, object userState) {
            if ((this.GetUserFriendsOperationCompleted == null)) {
                this.GetUserFriendsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserFriendsOperationCompleted);
            }
            this.InvokeAsync("GetUserFriends", new object[] {
                        initObj}, this.GetUserFriendsOperationCompleted, userState);
        }
        
        private void OnGetUserFriendsOperationCompleted(object arg) {
            if ((this.GetUserFriendsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserFriendsCompleted(this, new GetUserFriendsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://platform-us.tvinci.com/tvpapi/ws/FBConfig", RequestNamespace="http://platform-us.tvinci.com/tvpapi/ws", ResponseNamespace="http://platform-us.tvinci.com/tvpapi/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FBConnectConfig FBConfig(InitializationObject initObj, string sSTG) {
            object[] results = this.Invoke("FBConfig", new object[] {
                        initObj,
                        sSTG});
            return ((FBConnectConfig)(results[0]));
        }
        
        /// <remarks/>
        public void FBConfigAsync(InitializationObject initObj, string sSTG) {
            this.FBConfigAsync(initObj, sSTG, null);
        }
        
        /// <remarks/>
        public void FBConfigAsync(InitializationObject initObj, string sSTG, object userState) {
            if ((this.FBConfigOperationCompleted == null)) {
                this.FBConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFBConfigOperationCompleted);
            }
            this.InvokeAsync("FBConfig", new object[] {
                        initObj,
                        sSTG}, this.FBConfigOperationCompleted, userState);
        }
        
        private void OnFBConfigOperationCompleted(object arg) {
            if ((this.FBConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FBConfigCompleted(this, new FBConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform-us.tvinci.com/tvpapi/ws")]
    public partial class InitializationObject {
        
        private Locale localeField;
        
        private PlatformType platformField;
        
        private string siteGuidField;
        
        private int domainIDField;
        
        private string uDIDField;
        
        private string apiUserField;
        
        private string apiPassField;
        
        /// <remarks/>
        public Locale Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        public PlatformType Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string SiteGuid {
            get {
                return this.siteGuidField;
            }
            set {
                this.siteGuidField = value;
            }
        }
        
        /// <remarks/>
        public int DomainID {
            get {
                return this.domainIDField;
            }
            set {
                this.domainIDField = value;
            }
        }
        
        /// <remarks/>
        public string UDID {
            get {
                return this.uDIDField;
            }
            set {
                this.uDIDField = value;
            }
        }
        
        /// <remarks/>
        public string ApiUser {
            get {
                return this.apiUserField;
            }
            set {
                this.apiUserField = value;
            }
        }
        
        /// <remarks/>
        public string ApiPass {
            get {
                return this.apiPassField;
            }
            set {
                this.apiPassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform-us.tvinci.com/tvpapi/ws")]
    public partial class Locale {
        
        private string localeLanguageField;
        
        private string localeCountryField;
        
        private string localeDeviceField;
        
        private LocaleUserState localeUserStateField;
        
        /// <remarks/>
        public string LocaleLanguage {
            get {
                return this.localeLanguageField;
            }
            set {
                this.localeLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleCountry {
            get {
                return this.localeCountryField;
            }
            set {
                this.localeCountryField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleDevice {
            get {
                return this.localeDeviceField;
            }
            set {
                this.localeDeviceField = value;
            }
        }
        
        /// <remarks/>
        public LocaleUserState LocaleUserState {
            get {
                return this.localeUserStateField;
            }
            set {
                this.localeUserStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform-us.tvinci.com/tvpapi/ws")]
    public enum LocaleUserState {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Anonymous,
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Sub,
        
        /// <remarks/>
        ExSub,
        
        /// <remarks/>
        PPV,
        
        /// <remarks/>
        ExPPV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform-us.tvinci.com/tvpapi/ws")]
    public partial class FBConnectConfig {
        
        private string appIdField;
        
        private string scopeField;
        
        private string apiUserField;
        
        private string apiPassField;
        
        /// <remarks/>
        public string appId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
            }
        }
        
        /// <remarks/>
        public string scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        public string apiUser {
            get {
                return this.apiUserField;
            }
            set {
                this.apiUserField = value;
            }
        }
        
        /// <remarks/>
        public string apiPass {
            get {
                return this.apiPassField;
            }
            set {
                this.apiPassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://social.tvinci.com/")]
    public partial class FriendWatchedObject {
        
        private int siteGuidField;
        
        private int mediaIDField;
        
        private System.DateTime updateDateField;
        
        /// <remarks/>
        public int SiteGuid {
            get {
                return this.siteGuidField;
            }
            set {
                this.siteGuidField = value;
            }
        }
        
        /// <remarks/>
        public int MediaID {
            get {
                return this.mediaIDField;
            }
            set {
                this.mediaIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform-us.tvinci.com/tvpapi/ws")]
    public enum PlatformType {
        
        /// <remarks/>
        Web,
        
        /// <remarks/>
        STB,
        
        /// <remarks/>
        iPad,
        
        /// <remarks/>
        ConnectedTV,
        
        /// <remarks/>
        Cellular,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAllFriendsWatchedCompletedEventHandler(object sender, GetAllFriendsWatchedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllFriendsWatchedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllFriendsWatchedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FriendWatchedObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FriendWatchedObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetFriendsWatchedByMediaCompletedEventHandler(object sender, GetFriendsWatchedByMediaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFriendsWatchedByMediaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFriendsWatchedByMediaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FriendWatchedObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FriendWatchedObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetUsersLikedMediaCompletedEventHandler(object sender, GetUsersLikedMediaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersLikedMediaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersLikedMediaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetUserFriendsCompletedEventHandler(object sender, GetUserFriendsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserFriendsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserFriendsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void FBConfigCompletedEventHandler(object sender, FBConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FBConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FBConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FBConnectConfig Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FBConnectConfig)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591