// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;
using WebAPI.Models.Catalog;

namespace WebAPI.Models.Catalog.GroupRepresentatives
{
    [Serializable]
    public partial class KalturaTopSubscriptionEntitledRsp : KalturaRepresentativeSelectionPolicy
    {
        /// <summary>
        /// order by
        /// </summary>
        [DataMember(Name = "orderBy")]
        [JsonProperty("orderBy")]
        [XmlElement("orderBy", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [ValidationException(SchemeValidationType.FILTER_SUFFIX)]
        public KalturaBaseAssetOrder OrderBy { get; set; }
    }
}
