//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace M1BL.AdsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthorizationWebServiceSoapBinding", Namespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
    public partial class AuthorizationWebServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback canAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback canAccessVASOperationCompleted;
        
        private System.Threading.SendOrPostCallback canBatchAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback getScheduleBatchAccessResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback isWithinScheduleAndWithinBatchSizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback releaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback requestScheduledBatchAccessOperationCompleted;
        
        private System.Threading.SendOrPostCallback setScheduledBatchAccessResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthorizationWebServiceService() {
            this.Url = global::M1BL.Properties.Settings.Default.M1BL_AdsService_AuthorizationWebServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event canAccessCompletedEventHandler canAccessCompleted;
        
        /// <remarks/>
        public event canAccessVASCompletedEventHandler canAccessVASCompleted;
        
        /// <remarks/>
        public event canBatchAccessCompletedEventHandler canBatchAccessCompleted;
        
        /// <remarks/>
        public event checkJobCompletedEventHandler checkJobCompleted;
        
        /// <remarks/>
        public event getScheduleBatchAccessResultCompletedEventHandler getScheduleBatchAccessResultCompleted;
        
        /// <remarks/>
        public event isWithinScheduleAndWithinBatchSizeCompletedEventHandler isWithinScheduleAndWithinBatchSizeCompleted;
        
        /// <remarks/>
        public event releaseCompletedEventHandler releaseCompleted;
        
        /// <remarks/>
        public event requestScheduledBatchAccessCompletedEventHandler requestScheduledBatchAccessCompleted;
        
        /// <remarks/>
        public event setScheduledBatchAccessResultCompletedEventHandler setScheduledBatchAccessResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("canAccessReturn")]
        public string canAccess(string msisdn, string appID, string serviceID, string appPassword) {
            object[] results = this.Invoke("canAccess", new object[] {
                        msisdn,
                        appID,
                        serviceID,
                        appPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void canAccessAsync(string msisdn, string appID, string serviceID, string appPassword) {
            this.canAccessAsync(msisdn, appID, serviceID, appPassword, null);
        }
        
        /// <remarks/>
        public void canAccessAsync(string msisdn, string appID, string serviceID, string appPassword, object userState) {
            if ((this.canAccessOperationCompleted == null)) {
                this.canAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OncanAccessOperationCompleted);
            }
            this.InvokeAsync("canAccess", new object[] {
                        msisdn,
                        appID,
                        serviceID,
                        appPassword}, this.canAccessOperationCompleted, userState);
        }
        
        private void OncanAccessOperationCompleted(object arg) {
            if ((this.canAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.canAccessCompleted(this, new canAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("canAccessVASReturn")]
        public string[] canAccessVAS(string userID, string macAddress, string appID, string serviceID, string password) {
            object[] results = this.Invoke("canAccessVAS", new object[] {
                        userID,
                        macAddress,
                        appID,
                        serviceID,
                        password});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void canAccessVASAsync(string userID, string macAddress, string appID, string serviceID, string password) {
            this.canAccessVASAsync(userID, macAddress, appID, serviceID, password, null);
        }
        
        /// <remarks/>
        public void canAccessVASAsync(string userID, string macAddress, string appID, string serviceID, string password, object userState) {
            if ((this.canAccessVASOperationCompleted == null)) {
                this.canAccessVASOperationCompleted = new System.Threading.SendOrPostCallback(this.OncanAccessVASOperationCompleted);
            }
            this.InvokeAsync("canAccessVAS", new object[] {
                        userID,
                        macAddress,
                        appID,
                        serviceID,
                        password}, this.canAccessVASOperationCompleted, userState);
        }
        
        private void OncanAccessVASOperationCompleted(object arg) {
            if ((this.canAccessVASCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.canAccessVASCompleted(this, new canAccessVASCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("canBatchAccessReturn")]
        public string[] canBatchAccess(string[] msisdnList, string appID, string serviceID, string appPassword, bool continueOnFailure) {
            object[] results = this.Invoke("canBatchAccess", new object[] {
                        msisdnList,
                        appID,
                        serviceID,
                        appPassword,
                        continueOnFailure});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void canBatchAccessAsync(string[] msisdnList, string appID, string serviceID, string appPassword, bool continueOnFailure) {
            this.canBatchAccessAsync(msisdnList, appID, serviceID, appPassword, continueOnFailure, null);
        }
        
        /// <remarks/>
        public void canBatchAccessAsync(string[] msisdnList, string appID, string serviceID, string appPassword, bool continueOnFailure, object userState) {
            if ((this.canBatchAccessOperationCompleted == null)) {
                this.canBatchAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OncanBatchAccessOperationCompleted);
            }
            this.InvokeAsync("canBatchAccess", new object[] {
                        msisdnList,
                        appID,
                        serviceID,
                        appPassword,
                        continueOnFailure}, this.canBatchAccessOperationCompleted, userState);
        }
        
        private void OncanBatchAccessOperationCompleted(object arg) {
            if ((this.canBatchAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.canBatchAccessCompleted(this, new canBatchAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("checkJobReturn")]
        public bool checkJob(string handle) {
            object[] results = this.Invoke("checkJob", new object[] {
                        handle});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void checkJobAsync(string handle) {
            this.checkJobAsync(handle, null);
        }
        
        /// <remarks/>
        public void checkJobAsync(string handle, object userState) {
            if ((this.checkJobOperationCompleted == null)) {
                this.checkJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckJobOperationCompleted);
            }
            this.InvokeAsync("checkJob", new object[] {
                        handle}, this.checkJobOperationCompleted, userState);
        }
        
        private void OncheckJobOperationCompleted(object arg) {
            if ((this.checkJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkJobCompleted(this, new checkJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("getScheduleBatchAccessResultReturn")]
        public string[] getScheduleBatchAccessResult(string handle) {
            object[] results = this.Invoke("getScheduleBatchAccessResult", new object[] {
                        handle});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getScheduleBatchAccessResultAsync(string handle) {
            this.getScheduleBatchAccessResultAsync(handle, null);
        }
        
        /// <remarks/>
        public void getScheduleBatchAccessResultAsync(string handle, object userState) {
            if ((this.getScheduleBatchAccessResultOperationCompleted == null)) {
                this.getScheduleBatchAccessResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScheduleBatchAccessResultOperationCompleted);
            }
            this.InvokeAsync("getScheduleBatchAccessResult", new object[] {
                        handle}, this.getScheduleBatchAccessResultOperationCompleted, userState);
        }
        
        private void OngetScheduleBatchAccessResultOperationCompleted(object arg) {
            if ((this.getScheduleBatchAccessResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getScheduleBatchAccessResultCompleted(this, new getScheduleBatchAccessResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("isWithinScheduleAndWithinBatchSizeReturn")]
        public bool isWithinScheduleAndWithinBatchSize(string appID, string serviceID, int batchSize) {
            object[] results = this.Invoke("isWithinScheduleAndWithinBatchSize", new object[] {
                        appID,
                        serviceID,
                        batchSize});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isWithinScheduleAndWithinBatchSizeAsync(string appID, string serviceID, int batchSize) {
            this.isWithinScheduleAndWithinBatchSizeAsync(appID, serviceID, batchSize, null);
        }
        
        /// <remarks/>
        public void isWithinScheduleAndWithinBatchSizeAsync(string appID, string serviceID, int batchSize, object userState) {
            if ((this.isWithinScheduleAndWithinBatchSizeOperationCompleted == null)) {
                this.isWithinScheduleAndWithinBatchSizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisWithinScheduleAndWithinBatchSizeOperationCompleted);
            }
            this.InvokeAsync("isWithinScheduleAndWithinBatchSize", new object[] {
                        appID,
                        serviceID,
                        batchSize}, this.isWithinScheduleAndWithinBatchSizeOperationCompleted, userState);
        }
        
        private void OnisWithinScheduleAndWithinBatchSizeOperationCompleted(object arg) {
            if ((this.isWithinScheduleAndWithinBatchSizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isWithinScheduleAndWithinBatchSizeCompleted(this, new isWithinScheduleAndWithinBatchSizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        public void release(string handle) {
            this.Invoke("release", new object[] {
                        handle});
        }
        
        /// <remarks/>
        public void releaseAsync(string handle) {
            this.releaseAsync(handle, null);
        }
        
        /// <remarks/>
        public void releaseAsync(string handle, object userState) {
            if ((this.releaseOperationCompleted == null)) {
                this.releaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreleaseOperationCompleted);
            }
            this.InvokeAsync("release", new object[] {
                        handle}, this.releaseOperationCompleted, userState);
        }
        
        private void OnreleaseOperationCompleted(object arg) {
            if ((this.releaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.releaseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        [return: System.Xml.Serialization.SoapElementAttribute("requestScheduledBatchAccessReturn")]
        public string requestScheduledBatchAccess(string[] msisdnList, string appID, string serviceID, string appPassword, bool continueOnFailure) {
            object[] results = this.Invoke("requestScheduledBatchAccess", new object[] {
                        msisdnList,
                        appID,
                        serviceID,
                        appPassword,
                        continueOnFailure});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void requestScheduledBatchAccessAsync(string[] msisdnList, string appID, string serviceID, string appPassword, bool continueOnFailure) {
            this.requestScheduledBatchAccessAsync(msisdnList, appID, serviceID, appPassword, continueOnFailure, null);
        }
        
        /// <remarks/>
        public void requestScheduledBatchAccessAsync(string[] msisdnList, string appID, string serviceID, string appPassword, bool continueOnFailure, object userState) {
            if ((this.requestScheduledBatchAccessOperationCompleted == null)) {
                this.requestScheduledBatchAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestScheduledBatchAccessOperationCompleted);
            }
            this.InvokeAsync("requestScheduledBatchAccess", new object[] {
                        msisdnList,
                        appID,
                        serviceID,
                        appPassword,
                        continueOnFailure}, this.requestScheduledBatchAccessOperationCompleted, userState);
        }
        
        private void OnrequestScheduledBatchAccessOperationCompleted(object arg) {
            if ((this.requestScheduledBatchAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestScheduledBatchAccessCompleted(this, new requestScheduledBatchAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws", ResponseNamespace="http://ads1.m1.com.sg/ws/AuthorizationWebService.jws")]
        public void setScheduledBatchAccessResult(string[] result) {
            this.Invoke("setScheduledBatchAccessResult", new object[] {
                        result});
        }
        
        /// <remarks/>
        public void setScheduledBatchAccessResultAsync(string[] result) {
            this.setScheduledBatchAccessResultAsync(result, null);
        }
        
        /// <remarks/>
        public void setScheduledBatchAccessResultAsync(string[] result, object userState) {
            if ((this.setScheduledBatchAccessResultOperationCompleted == null)) {
                this.setScheduledBatchAccessResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetScheduledBatchAccessResultOperationCompleted);
            }
            this.InvokeAsync("setScheduledBatchAccessResult", new object[] {
                        result}, this.setScheduledBatchAccessResultOperationCompleted, userState);
        }
        
        private void OnsetScheduledBatchAccessResultOperationCompleted(object arg) {
            if ((this.setScheduledBatchAccessResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setScheduledBatchAccessResultCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void canAccessCompletedEventHandler(object sender, canAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class canAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal canAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void canAccessVASCompletedEventHandler(object sender, canAccessVASCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class canAccessVASCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal canAccessVASCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void canBatchAccessCompletedEventHandler(object sender, canBatchAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class canBatchAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal canBatchAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void checkJobCompletedEventHandler(object sender, checkJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getScheduleBatchAccessResultCompletedEventHandler(object sender, getScheduleBatchAccessResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getScheduleBatchAccessResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getScheduleBatchAccessResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void isWithinScheduleAndWithinBatchSizeCompletedEventHandler(object sender, isWithinScheduleAndWithinBatchSizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isWithinScheduleAndWithinBatchSizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isWithinScheduleAndWithinBatchSizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void releaseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void requestScheduledBatchAccessCompletedEventHandler(object sender, requestScheduledBatchAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestScheduledBatchAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal requestScheduledBatchAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void setScheduledBatchAccessResultCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591