ARG BUILD_TAG=latest
ARG WINDOWS_TAG=ltsc2019
FROM kaltura/phoenix-build:${BUILD_TAG} AS builder


FROM mcr.microsoft.com/windows/servercore:${WINDOWS_TAG}
SHELL ["powershell"]

COPY --from=builder ConfigurationValidator\bin\Release\ConfigurationValidator.exe ConfigurationValidator.exe

CMD ConfigurationValidator.exe
	
RUN $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo('C:\ConfigurationValidator.exe').FileVersion; \
	Set-Content -Path 'C:\VERSION' -Value $version
