// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using System;

namespace WebAPI.Models.Pricing
{
    [Serializable]
    public enum KalturaAssetFilePpvOrderBy
    {
        NONE = 0
    }
}
