//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Users.KDGApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KDGApi.IMockKdgService")]
    public interface IMockKdgService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMockKdgService/authenticate", ReplyAction="http://tempuri.org/IMockKdgService/authenticateResponse")]
        long authenticate(string username, string password, string clientIp, out string accountnr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMockKdgServiceChannel : Users.KDGApi.IMockKdgService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MockKdgServiceClient : System.ServiceModel.ClientBase<Users.KDGApi.IMockKdgService>, Users.KDGApi.IMockKdgService {
        
        public MockKdgServiceClient() {
        }
        
        public MockKdgServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MockKdgServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MockKdgServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MockKdgServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public long authenticate(string username, string password, string clientIp, out string accountnr)
        {
            return base.Channel.authenticate(username, password, clientIp, out accountnr);
        }
    }
}
