// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: TechnicalData.xsd
// Creation Date: 29/01/2013 11:26:04
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace TVPPro.Configuration.Technical
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}

	[Serializable]
	public enum ActionOnUnknownKey
	{
		[XmlEnum(Name="ShowHyphen")] ShowHyphen,
		[XmlEnum(Name="ShowKey")] ShowKey,
		[XmlEnum(Name="ShowNothing")] ShowNothing
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class CharacterCollection : ArrayList
	{
		public Character Add(Character obj)
		{
			base.Add(obj);
			return obj;
		}

		public Character Add()
		{
			return Add(new Character());
		}

		public void Insert(int index, Character obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(Character obj)
		{
			base.Remove(obj);
		}

		new public Character this[int index]
		{
			get { return (Character) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlType(TypeName="Server"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class Server
	{

		[XmlAttribute(AttributeName="ID",Form=XmlSchemaForm.Unqualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __ID;
		
		[XmlIgnore]
		public string ID
		{ 
			get { return __ID; }
			set { __ID = value; }
		}

		[XmlElement(ElementName="URL",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __URL;
		
		[XmlIgnore]
		public string URL
		{ 
			get { return __URL; }
			set { __URL = value; }
		}

		[XmlElement(ElementName="TVMReadURL",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __TVMReadURL;
		
		[XmlIgnore]
		public string TVMReadURL
		{ 
			get { return __TVMReadURL; }
			set { __TVMReadURL = value; }
		}

		[XmlElement(ElementName="TVMWriteURL",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __TVMWriteURL;
		
		[XmlIgnore]
		public string TVMWriteURL
		{ 
			get { return __TVMWriteURL; }
			set { __TVMWriteURL = value; }
		}

		public Server()
		{
			URL = string.Empty;
			TVMReadURL = string.Empty;
			TVMWriteURL = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="BrandingType"),Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class BrandingType
	{

		[XmlElement(ElementName="BrandingMainFormat",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BrandingMainFormat;
		
		[XmlIgnore]
		public string BrandingMainFormat
		{ 
			get { return __BrandingMainFormat; }
			set { __BrandingMainFormat = value; }
		}

		[XmlElement(ElementName="BrandingPicSize",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BrandingPicSize;
		
		[XmlIgnore]
		public string BrandingPicSize
		{ 
			get { return __BrandingPicSize; }
			set { __BrandingPicSize = value; }
		}

		[XmlElement(ElementName="BrandingRepeatFormat",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BrandingRepeatFormat;
		
		[XmlIgnore]
		public string BrandingRepeatFormat
		{ 
			get { return __BrandingRepeatFormat; }
			set { __BrandingRepeatFormat = value; }
		}

		public BrandingType()
		{
			BrandingMainFormat = string.Empty;
			BrandingPicSize = string.Empty;
			BrandingRepeatFormat = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlRoot(ElementName="TechnicalData",IsNullable=false),Serializable]
	public partial class TechnicalData
	{

		[XmlElement(Type=typeof(DBConfiguration),ElementName="DBConfiguration",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DBConfiguration __DBConfiguration;
		
		[XmlIgnore]
		public DBConfiguration DBConfiguration
		{
			get
			{
				if (__DBConfiguration == null) __DBConfiguration = new DBConfiguration();		
				return __DBConfiguration;
			}
			set {__DBConfiguration = value;}
		}

		[XmlElement(Type=typeof(TVM),ElementName="TVM",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public TVM __TVM;
		
		[XmlIgnore]
		public TVM TVM
		{
			get
			{
				if (__TVM == null) __TVM = new TVM();		
				return __TVM;
			}
			set {__TVM = value;}
		}

		[XmlElement(Type=typeof(Translation),ElementName="Translation",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Translation __Translation;
		
		[XmlIgnore]
		public Translation Translation
		{
			get
			{
				if (__Translation == null) __Translation = new Translation();		
				return __Translation;
			}
			set {__Translation = value;}
		}

		[XmlElement(Type=typeof(Site),ElementName="Site",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Site __Site;
		
		[XmlIgnore]
		public Site Site
		{
			get
			{
				if (__Site == null) __Site = new Site();		
				return __Site;
			}
			set {__Site = value;}
		}

		[XmlElement(Type=typeof(Billing),ElementName="Billing",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Billing __Billing;
		
		[XmlIgnore]
		public Billing Billing
		{
			get
			{
				if (__Billing == null) __Billing = new Billing();		
				return __Billing;
			}
			set {__Billing = value;}
		}

        [XmlElement(Type = typeof(Player), ElementName = "Player", IsNullable = false, Form = XmlSchemaForm.Qualified)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public Player __Player;

        [XmlIgnore]
        public Player Player
        {
            get
            {
                if (__Player == null) __Player = new Player();
                return __Player;
            }
            set { __Player = value; }
        }

		public TechnicalData()
		{
		}

		public void MakeSchemaCompliant()
		{
			DBConfiguration.MakeSchemaCompliant();
			TVM.MakeSchemaCompliant();
			Translation.MakeSchemaCompliant();
			Site.MakeSchemaCompliant();
			Billing.MakeSchemaCompliant();
            Player.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="DBConfiguration"),Serializable]
	public partial class DBConfiguration
	{

		[XmlElement(ElementName="User",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __User;
		
		[XmlIgnore]
		public string User
		{ 
			get { return __User; }
			set { __User = value; }
		}

		[XmlElement(ElementName="Pass",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Pass;
		
		[XmlIgnore]
		public string Pass
		{ 
			get { return __Pass; }
			set { __Pass = value; }
		}

		[XmlElement(ElementName="IP",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __IP;
		
		[XmlIgnore]
		public string IP
		{ 
			get { return __IP; }
			set { __IP = value; }
		}

		[XmlElement(ElementName="DatabaseInstance",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __DatabaseInstance;
		
		[XmlIgnore]
		public string DatabaseInstance
		{ 
			get { return __DatabaseInstance; }
			set { __DatabaseInstance = value; }
		}

		public DBConfiguration()
		{
			User = string.Empty;
			Pass = string.Empty;
			IP = string.Empty;
			DatabaseInstance = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="TVM"),Serializable]
	public partial class TVM
	{

		[XmlElement(Type=typeof(Servers),ElementName="Servers",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Servers __Servers;
		
		[XmlIgnore]
		public Servers Servers
		{
			get
			{
				if (__Servers == null) __Servers = new Servers();		
				return __Servers;
			}
			set {__Servers = value;}
		}

		[XmlElement(Type=typeof(Configuration),ElementName="Configuration",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Configuration __Configuration;
		
		[XmlIgnore]
		public Configuration Configuration
		{
			get
			{
				if (__Configuration == null) __Configuration = new Configuration();		
				return __Configuration;
			}
			set {__Configuration = value;}
		}

		[XmlElement(Type=typeof(CachingServer),ElementName="CachingServer",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CachingServer __CachingServer;
		
		[XmlIgnore]
		public CachingServer CachingServer
		{
			get
			{
				if (__CachingServer == null) __CachingServer = new CachingServer();		
				return __CachingServer;
			}
			set {__CachingServer = value;}
		}

		[XmlElement(Type=typeof(FlashVars),ElementName="FlashVars",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public FlashVars __FlashVars;
		
		[XmlIgnore]
		public FlashVars FlashVars
		{
			get
			{
				if (__FlashVars == null) __FlashVars = new FlashVars();		
				return __FlashVars;
			}
			set {__FlashVars = value;}
		}

		[XmlElement(ElementName="TVMRssURL",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __TVMRssURL;
		
		[XmlIgnore]
		public string TVMRssURL
		{ 
			get { return __TVMRssURL; }
			set { __TVMRssURL = value; }
		}

		public TVM()
		{
			TVMRssURL = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
			Servers.MakeSchemaCompliant();
			Configuration.MakeSchemaCompliant();
			CachingServer.MakeSchemaCompliant();
			FlashVars.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="Servers"),Serializable]
	public partial class Servers
	{

		[XmlElement(Type=typeof(TVPPro.Configuration.Technical.Server),ElementName="MainServer",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public TVPPro.Configuration.Technical.Server __MainServer;
		
		[XmlIgnore]
		public TVPPro.Configuration.Technical.Server MainServer
		{
			get
			{
				if (__MainServer == null) __MainServer = new TVPPro.Configuration.Technical.Server();		
				return __MainServer;
			}
			set {__MainServer = value;}
		}

		[XmlElement(Type=typeof(TVPPro.Configuration.Technical.Server),ElementName="AlternativeServer",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public TVPPro.Configuration.Technical.Server __AlternativeServer;
		
		[XmlIgnore]
		public TVPPro.Configuration.Technical.Server AlternativeServer
		{
			get
			{
				if (__AlternativeServer == null) __AlternativeServer = new TVPPro.Configuration.Technical.Server();		
				return __AlternativeServer;
			}
			set {__AlternativeServer = value;}
		}

		public Servers()
		{
		}

		public void MakeSchemaCompliant()
		{
			MainServer.MakeSchemaCompliant();
			AlternativeServer.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="Configuration"),Serializable]
	public partial class Configuration
	{

		[XmlElement(ElementName="ForceUpdatedData",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ForceUpdatedData;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ForceUpdatedDataSpecified;
		
		[XmlIgnore]
		public bool ForceUpdatedData
		{ 
			get { return __ForceUpdatedData; }
			set { __ForceUpdatedData = value; __ForceUpdatedDataSpecified = true; }
		}

		[XmlElement(ElementName="EnableTimer",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __EnableTimer;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __EnableTimerSpecified;
		
		[XmlIgnore]
		public bool EnableTimer
		{ 
			get { return __EnableTimer; }
			set { __EnableTimer = value; __EnableTimerSpecified = true; }
		}

		[XmlElement(ElementName="User",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __User;
		
		[XmlIgnore]
		public string User
		{ 
			get { return __User; }
			set { __User = value; }
		}

		[XmlElement(ElementName="Password",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Password;
		
		[XmlIgnore]
		public string Password
		{ 
			get { return __Password; }
			set { __Password = value; }
		}

		[XmlElement(ElementName="EmbedUser",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __EmbedUser;
		
		[XmlIgnore]
		public string EmbedUser
		{ 
			get { return __EmbedUser; }
			set { __EmbedUser = value; }
		}

		[XmlElement(ElementName="EmberPassword",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __EmberPassword;
		
		[XmlIgnore]
		public string EmberPassword
		{ 
			get { return __EmberPassword; }
			set { __EmberPassword = value; }
		}

		public Configuration()
		{
			__ForceUpdatedDataSpecified = true;
			__EnableTimerSpecified = true;
			User = string.Empty;
			Password = string.Empty;
			EmbedUser = string.Empty;
			EmberPassword = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="CachingServer"),Serializable]
	public partial class CachingServer
	{

		[XmlElement(ElementName="AllowedIPs",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __AllowedIPs;
		
		[XmlIgnore]
		public string AllowedIPs
		{ 
			get { return __AllowedIPs; }
			set { __AllowedIPs = value; }
		}

		public CachingServer()
		{
			AllowedIPs = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="FlashVars"),Serializable]
	public partial class FlashVars
	{

		[XmlElement(ElementName="FileFormat",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __FileFormat;
		
		[XmlIgnore]
		public string FileFormat
		{ 
			get { return __FileFormat; }
			set { __FileFormat = value; }
		}

		[XmlElement(ElementName="SubFileFormat",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SubFileFormat;
		
		[XmlIgnore]
		public string SubFileFormat
		{ 
			get { return __SubFileFormat; }
			set { __SubFileFormat = value; }
		}

		[XmlElement(Type=typeof(Branding),ElementName="Branding",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Branding __Branding;
		
		[XmlIgnore]
		public Branding Branding
		{
			get
			{
				if (__Branding == null) __Branding = new Branding();		
				return __Branding;
			}
			set {__Branding = value;}
		}

		public FlashVars()
		{
			FileFormat = string.Empty;
			SubFileFormat = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
			Branding.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="Branding"),Serializable]
	public partial class Branding
	{

		[XmlElement(Type=typeof(TVPPro.Configuration.Technical.BrandingType),ElementName="BrandingRegular",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public TVPPro.Configuration.Technical.BrandingType __BrandingRegular;
		
		[XmlIgnore]
		public TVPPro.Configuration.Technical.BrandingType BrandingRegular
		{
			get
			{
				if (__BrandingRegular == null) __BrandingRegular = new TVPPro.Configuration.Technical.BrandingType();		
				return __BrandingRegular;
			}
			set {__BrandingRegular = value;}
		}

		[XmlElement(Type=typeof(TVPPro.Configuration.Technical.BrandingType),ElementName="BrandingVirtual",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public TVPPro.Configuration.Technical.BrandingType __BrandingVirtual;
		
		[XmlIgnore]
		public TVPPro.Configuration.Technical.BrandingType BrandingVirtual
		{
			get
			{
				if (__BrandingVirtual == null) __BrandingVirtual = new TVPPro.Configuration.Technical.BrandingType();		
				return __BrandingVirtual;
			}
			set {__BrandingVirtual = value;}
		}

		public Branding()
		{
		}

		public void MakeSchemaCompliant()
		{
			BrandingRegular.MakeSchemaCompliant();
			BrandingVirtual.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="Translation"),Serializable]
	public partial class Translation
	{

		[XmlAttribute(AttributeName="UseTranslatedMediaType",Form=XmlSchemaForm.Unqualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __UseTranslatedMediaType;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __UseTranslatedMediaTypeSpecified;
		
		[XmlIgnore]
		public bool UseTranslatedMediaType
		{ 
			get { return __UseTranslatedMediaType; }
			set { __UseTranslatedMediaType = value; __UseTranslatedMediaTypeSpecified = true; }
		}

		[XmlElement(ElementName="Culture",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Culture;
		
		[XmlIgnore]
		public string Culture
		{ 
			get { return __Culture; }
			set { __Culture = value; }
		}

		[XmlElement(Type=typeof(CharacterReplace),ElementName="CharacterReplace",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CharacterReplace __CharacterReplace;
		
		[XmlIgnore]
		public CharacterReplace CharacterReplace
		{
			get
			{
				if (__CharacterReplace == null) __CharacterReplace = new CharacterReplace();		
				return __CharacterReplace;
			}
			set {__CharacterReplace = value;}
		}

		[XmlElement(ElementName="ActionOnUnknownKey",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ActionOnUnknownKey __ActionOnUnknownKey;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __ActionOnUnknownKeySpecified;
		
		[XmlIgnore]
		public ActionOnUnknownKey ActionOnUnknownKey
		{ 
			get { return __ActionOnUnknownKey; }
			set { __ActionOnUnknownKey = value; __ActionOnUnknownKeySpecified = true; }
		}

		public Translation()
		{
			UseTranslatedMediaType = false;
			Culture = string.Empty;
			ActionOnUnknownKey = ActionOnUnknownKey.ShowHyphen;
		}

		public void MakeSchemaCompliant()
		{
			CharacterReplace.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="CharacterReplace"),Serializable]
	public partial class CharacterReplace
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return CharacterCollection.GetEnumerator();
		}

		public Character Add(Character obj)
		{
			return CharacterCollection.Add(obj);
		}

		[XmlIgnore]
		public Character this[int index]
		{
			get { return (Character) CharacterCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return CharacterCollection.Count; }
        }

        public void Clear()
		{
			CharacterCollection.Clear();
        }

		public Character Remove(int index) 
		{ 
            Character obj = CharacterCollection[index];
            CharacterCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            CharacterCollection.Remove(obj);
        }

		[XmlAttribute(AttributeName="SupportFeature",Form=XmlSchemaForm.Unqualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SupportFeature;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SupportFeatureSpecified;
		
		[XmlIgnore]
		public bool SupportFeature
		{ 
			get { return __SupportFeature; }
			set { __SupportFeature = value; __SupportFeatureSpecified = true; }
		}

		[XmlElement(Type=typeof(Character),ElementName="Character",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CharacterCollection __CharacterCollection;
		
		[XmlIgnore]
		public CharacterCollection CharacterCollection
		{
			get
			{
				if (__CharacterCollection == null) __CharacterCollection = new CharacterCollection();
				return __CharacterCollection;
			}
			set {__CharacterCollection = value;}
		}

		public CharacterReplace()
		{
			SupportFeature = false;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="Character"),Serializable]
	public partial class Character
	{

		[XmlAttribute(AttributeName="OldChar",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __OldChar;
		
		[XmlIgnore]
		public string OldChar
		{ 
			get { return __OldChar; }
			set { __OldChar = value; }
		}

		[XmlAttribute(AttributeName="NewChar",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __NewChar;
		
		[XmlIgnore]
		public string NewChar
		{ 
			get { return __NewChar; }
			set { __NewChar = value; }
		}

		public Character()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="Site"),Serializable]
	public partial class Site
	{

		[XmlElement(ElementName="BasePictureUrl",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BasePictureUrl;
		
		[XmlIgnore]
		public string BasePictureUrl
		{ 
			get { return __BasePictureUrl; }
			set { __BasePictureUrl = value; }
		}

		[XmlElement(Type=typeof(GalleryComponent),ElementName="GalleryComponent",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public GalleryComponent __GalleryComponent;
		
		[XmlIgnore]
		public GalleryComponent GalleryComponent
		{
			get
			{
				if (__GalleryComponent == null) __GalleryComponent = new GalleryComponent();		
				return __GalleryComponent;
			}
			set {__GalleryComponent = value;}
		}

		[XmlElement(Type=typeof(ApplicativeBaseUri),ElementName="ApplicativeBaseUri",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public ApplicativeBaseUri __ApplicativeBaseUri;
		
		[XmlIgnore]
		public ApplicativeBaseUri ApplicativeBaseUri
		{
			get
			{
				if (__ApplicativeBaseUri == null) __ApplicativeBaseUri = new ApplicativeBaseUri();		
				return __ApplicativeBaseUri;
			}
			set {__ApplicativeBaseUri = value;}
		}

		[XmlElement(ElementName="LogBasePath",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __LogBasePath;
		
		[XmlIgnore]
		public string LogBasePath
		{ 
			get { return __LogBasePath; }
			set { __LogBasePath = value; }
		}

		[XmlElement(Type=typeof(CDNUrl),ElementName="CDNUrl",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public CDNUrl __CDNUrl;
		
		[XmlIgnore]
		public CDNUrl CDNUrl
		{
			get
			{
				if (__CDNUrl == null) __CDNUrl = new CDNUrl();		
				return __CDNUrl;
			}
			set {__CDNUrl = value;}
		}

		public Site()
		{
			BasePictureUrl = string.Empty;
			LogBasePath = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
			GalleryComponent.MakeSchemaCompliant();
			ApplicativeBaseUri.MakeSchemaCompliant();
			CDNUrl.MakeSchemaCompliant();
		}
	}

    [XmlType(TypeName = "Player"), Serializable]
    public partial class Player
    {

        [XmlElement(ElementName = "MainFileFormat", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __MainFileFormat;

        [XmlIgnore]
        public string MainFileFormat
        {
            get { return __MainFileFormat; }
            set { __MainFileFormat = value; }
        }

        [XmlElement(ElementName = "TrailerFileFormat", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __TrailerFileFormat;

        [XmlIgnore]
        public string TrailerFileFormat
        {
            get { return __TrailerFileFormat; }
            set { __TrailerFileFormat = value; }
        }

        [XmlElement(ElementName = "TrickPlayFileFormat", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __TrickPlayFileFormat;

        [XmlIgnore]
        public string TrickPlayFileFormat
        {
            get { return __TrickPlayFileFormat; }
            set { __TrickPlayFileFormat = value; }
        }


        [XmlElement(ElementName = "BlackoutFileFormat", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __BlackoutFileFormat;

        [XmlIgnore]
        public string BlackoutFileFormat
        {
            get { return __BlackoutFileFormat; }
            set { __BlackoutFileFormat = value; }
        }

        public Player()
        {
            MainFileFormat = string.Empty;
            TrailerFileFormat = string.Empty;
            TrickPlayFileFormat = string.Empty;
            BlackoutFileFormat = string.Empty;
        }

        public void MakeSchemaCompliant()
        {
        }
    }


	[XmlType(TypeName="GalleryComponent"),Serializable]
	public partial class GalleryComponent
	{

		[XmlAttribute(AttributeName="NonAjaxGalleriesNumber",Form=XmlSchemaForm.Unqualified,DataType="int")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __NonAjaxGalleriesNumber;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __NonAjaxGalleriesNumberSpecified;
		
		[XmlIgnore]
		public int NonAjaxGalleriesNumber
		{ 
			get { return __NonAjaxGalleriesNumber; }
			set { __NonAjaxGalleriesNumber = value; __NonAjaxGalleriesNumberSpecified = true; }
		}

		[XmlElement(ElementName="SWFFileBaseURL",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SWFFileBaseURL;
		
		[XmlIgnore]
		public string SWFFileBaseURL
		{ 
			get { return __SWFFileBaseURL; }
			set { __SWFFileBaseURL = value; }
		}

		public GalleryComponent()
		{
			NonAjaxGalleriesNumber = 3;
			SWFFileBaseURL = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="ApplicativeBaseUri"),Serializable]
	public partial class ApplicativeBaseUri
	{

		[XmlAttribute(AttributeName="UsePermanentURL",Form=XmlSchemaForm.Unqualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __UsePermanentURL;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __UsePermanentURLSpecified;
		
		[XmlIgnore]
		public bool UsePermanentURL
		{ 
			get { return __UsePermanentURL; }
			set { __UsePermanentURL = value; __UsePermanentURLSpecified = true; }
		}

		[XmlElement(ElementName="SecureBaseUri",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __SecureBaseUri;
		
		[XmlIgnore]
		public string SecureBaseUri
		{ 
			get { return __SecureBaseUri; }
			set { __SecureBaseUri = value; }
		}

		[XmlElement(ElementName="BaseUri",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __BaseUri;
		
		[XmlIgnore]
		public string BaseUri
		{ 
			get { return __BaseUri; }
			set { __BaseUri = value; }
		}

		public ApplicativeBaseUri()
		{
			UsePermanentURL = false;
			SecureBaseUri = string.Empty;
			BaseUri = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="CDNUrl"),Serializable]
	public partial class CDNUrl
	{

		[XmlElement(ElementName="Source",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Source;
		
		[XmlIgnore]
		public string Source
		{ 
			get { return __Source; }
			set { __Source = value; }
		}

        [XmlElement(ElementName = "Resource", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __Resource;

        [XmlIgnore]
        public string Resource
        {
            get { return __Resource; }
            set { __Resource = value; }
        }

		[XmlElement(ElementName="Preloader",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Preloader;
		
		[XmlIgnore]
		public string Preloader
		{ 
			get { return __Preloader; }
			set { __Preloader = value; }
		}

        [XmlElement(ElementName = "DeviceDNA", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __DeviceDNA;

        [XmlIgnore]
        public string DeviceDNA
        {
            get { return __DeviceDNA; }
            set { __DeviceDNA = value; }
        }

        [XmlElement(ElementName = "InitialMediaID", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __InitialMediaID;

        [XmlIgnore]
        public string InitialMediaID
        {
            get { return __InitialMediaID; }
            set { __InitialMediaID = value; }
        }

		public CDNUrl()
		{
			Source = string.Empty;
			Preloader = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="Billing"),Serializable]
	public partial class Billing
	{

		[XmlAttribute(AttributeName="SupportFeature",Form=XmlSchemaForm.Unqualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SupportFeature;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __SupportFeatureSpecified;
		
		[XmlIgnore]
		public bool SupportFeature
		{ 
			get { return __SupportFeature; }
			set { __SupportFeature = value; __SupportFeatureSpecified = true; }
		}

		[XmlAttribute(AttributeName="HTMLProcess",Form=XmlSchemaForm.Unqualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HTMLProcess;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __HTMLProcessSpecified;
		
		[XmlIgnore]
		public bool HTMLProcess
		{ 
			get { return __HTMLProcess; }
			set { __HTMLProcess = value; __HTMLProcessSpecified = true; }
		}

		[XmlElement(ElementName="Processor",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Processor;
		
		[XmlIgnore]
		public string Processor
		{ 
			get { return __Processor; }
			set { __Processor = value; }
		}

		[XmlElement(ElementName="Account",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Account;
		
		[XmlIgnore]
		public string Account
		{ 
			get { return __Account; }
			set { __Account = value; }
		}

		public Billing()
		{
			SupportFeature = false;
			HTMLProcess = false;
			Processor = string.Empty;
			Account = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}
}
