//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdapterControllers.drmAdapter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdapterStatus", Namespace="http://schemas.datacontract.org/2004/07/PGAdapterCommon.Models")]
    [System.SerializableAttribute()]
    public partial class AdapterStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetType", Namespace="http://schemas.datacontract.org/2004/07/DRMAdapter")]
    public enum AssetType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EPG = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RECORDING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VOD = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrmAdapterResponse", Namespace="http://schemas.datacontract.org/2004/07/DRMAdapter")]
    [System.SerializableAttribute()]
    public partial class DrmAdapterResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.drmAdapter.AdapterStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderResponse {
            get {
                return this.ProviderResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderResponseField, value) != true)) {
                    this.ProviderResponseField = value;
                    this.RaisePropertyChanged("ProviderResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.drmAdapter.AdapterStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="drmAdapter.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetConfiguration", ReplyAction="http://tempuri.org/IService/SetConfigurationResponse")]
        AdapterControllers.drmAdapter.AdapterStatus SetConfiguration(int adapterId, string settings, int partnerId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetConfiguration", ReplyAction="http://tempuri.org/IService/SetConfigurationResponse")]
        System.Threading.Tasks.Task<AdapterControllers.drmAdapter.AdapterStatus> SetConfigurationAsync(int adapterId, string settings, int partnerId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAssetLicenseData", ReplyAction="http://tempuri.org/IService/GetAssetLicenseDataResponse")]
        AdapterControllers.drmAdapter.DrmAdapterResponse GetAssetLicenseData(int adapterId, int partnerId, string userId, string assetId, AdapterControllers.drmAdapter.AssetType assetType, long fileId, string externalFileId, string ip, string udid, int deviceBrandId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAssetLicenseData", ReplyAction="http://tempuri.org/IService/GetAssetLicenseDataResponse")]
        System.Threading.Tasks.Task<AdapterControllers.drmAdapter.DrmAdapterResponse> GetAssetLicenseDataAsync(int adapterId, int partnerId, string userId, string assetId, AdapterControllers.drmAdapter.AssetType assetType, long fileId, string externalFileId, string ip, string udid, int deviceBrandId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDeviceLicenseData", ReplyAction="http://tempuri.org/IService/GetDeviceLicenseDataResponse")]
        AdapterControllers.drmAdapter.DrmAdapterResponse GetDeviceLicenseData(int adapterId, int partnerId, string userId, string udid, string deviceFamily, int deviceBrandId, string ip, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDeviceLicenseData", ReplyAction="http://tempuri.org/IService/GetDeviceLicenseDataResponse")]
        System.Threading.Tasks.Task<AdapterControllers.drmAdapter.DrmAdapterResponse> GetDeviceLicenseDataAsync(int adapterId, int partnerId, string userId, string udid, string deviceFamily, int deviceBrandId, string ip, long timeStamp, string signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : AdapterControllers.drmAdapter.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<AdapterControllers.drmAdapter.IService>, AdapterControllers.drmAdapter.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdapterControllers.drmAdapter.AdapterStatus SetConfiguration(int adapterId, string settings, int partnerId, long timeStamp, string signature) {
            return base.Channel.SetConfiguration(adapterId, settings, partnerId, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.drmAdapter.AdapterStatus> SetConfigurationAsync(int adapterId, string settings, int partnerId, long timeStamp, string signature) {
            return base.Channel.SetConfigurationAsync(adapterId, settings, partnerId, timeStamp, signature);
        }
        
        public AdapterControllers.drmAdapter.DrmAdapterResponse GetAssetLicenseData(int adapterId, int partnerId, string userId, string assetId, AdapterControllers.drmAdapter.AssetType assetType, long fileId, string externalFileId, string ip, string udid, int deviceBrandId, long timeStamp, string signature) {
            return base.Channel.GetAssetLicenseData(adapterId, partnerId, userId, assetId, assetType, fileId, externalFileId, ip, udid, deviceBrandId, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.drmAdapter.DrmAdapterResponse> GetAssetLicenseDataAsync(int adapterId, int partnerId, string userId, string assetId, AdapterControllers.drmAdapter.AssetType assetType, long fileId, string externalFileId, string ip, string udid, int deviceBrandId, long timeStamp, string signature) {
            return base.Channel.GetAssetLicenseDataAsync(adapterId, partnerId, userId, assetId, assetType, fileId, externalFileId, ip, udid, deviceBrandId, timeStamp, signature);
        }
        
        public AdapterControllers.drmAdapter.DrmAdapterResponse GetDeviceLicenseData(int adapterId, int partnerId, string userId, string udid, string deviceFamily, int deviceBrandId, string ip, long timeStamp, string signature) {
            return base.Channel.GetDeviceLicenseData(adapterId, partnerId, userId, udid, deviceFamily, deviceBrandId, ip, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.drmAdapter.DrmAdapterResponse> GetDeviceLicenseDataAsync(int adapterId, int partnerId, string userId, string udid, string deviceFamily, int deviceBrandId, string ip, long timeStamp, string signature) {
            return base.Channel.GetDeviceLicenseDataAsync(adapterId, partnerId, userId, udid, deviceFamily, deviceBrandId, ip, timeStamp, signature);
        }
    }
}
