// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using System;
using WebAPI.Models.General;

namespace WebAPI.Models.Catalog
{
    [Serializable]
    public abstract partial class KalturaBaseAssetOrder : KalturaOTTObject
    {
    }
}
