// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;

namespace WebAPI.Models.Catalog
{
    [Serializable]
    public partial class KalturaBundleFilter : KalturaAssetFilter
    {
        /// <summary>
        /// Bundle Id.
        /// </summary>
        [DataMember(Name = "idEqual")]
        [JsonProperty("idEqual")]
        [XmlElement("idEqual")]
        [SchemeProperty(MinInteger = 1)]
        public int IdEqual { get; set; }

        /// <summary>
        /// Comma separated list of asset types to search within.
        /// Possible values: 0 - EPG linear programs entries, any media type ID (according to media type IDs defined dynamically in the system).
        /// If omitted - all types should be included.
        /// </summary>
        [DataMember(Name = "typeIn")]
        [JsonProperty("typeIn")]
        [XmlElement("typeIn", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public string TypeIn { get; set; }

        /// <summary>
        /// bundleType - possible values: Subscription or Collection
        /// </summary>
        [DataMember(Name = "bundleTypeEqual")]
        [JsonProperty("bundleTypeEqual")]
        [XmlElement("bundleTypeEqual")]
        public KalturaBundleType BundleTypeEqual { get; set; }
    }
}
