// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;
using WebAPI.Models.General;

namespace WebAPI.Models.Catalog
{
    /// <summary>
    /// Asset info
    /// </summary>
    [Serializable]
    [Obsolete]
    public partial class KalturaAssetInfo : KalturaBaseAssetInfo, KalturaIAssetable
    {
        /// <summary>
        /// Dynamic collection of key-value pairs according to the String Meta defined in the system
        /// </summary>
        [DataMember(Name = "metas")]
        [JsonProperty("metas")]
        [XmlElement("metas", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public SerializableDictionary<string, KalturaValue> Metas { get; set; }

        /// <summary>
        /// Dynamic collection of key-value pairs according to the Tag Types defined in the system
        /// </summary>
        [DataMember(Name = "tags")]
        [JsonProperty("tags")]
        [XmlElement("tags", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public SerializableDictionary<string, KalturaMultilingualStringValueArray> Tags { get; set; }

        /// <summary>
        /// Date and time represented as epoch. For VOD - since when the asset is available in the catalog. For EPG/Linear - when the program is aired (can be in the future).
        /// </summary>
        [DataMember(Name = "startDate")]
        [JsonProperty("startDate")]
        [XmlElement("startDate", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("start_date")]
        public long? StartDate { get; set; }

        /// <summary>
        /// Date and time represented as epoch. For VOD - till when the asset be available in the catalog. For EPG/Linear - program end time and date
        /// </summary>
        [DataMember(Name = "endDate")]
        [JsonProperty("endDate")]
        [XmlElement("endDate", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("end_date")]
        public long? EndDate { get; set; }

        /// <summary>
        /// A collection of additional key value pairs that are available per asset type. Possible keys: 
        /// For 0 (EPG linear programs): epg_channel_id - The EPG channel ID, epg_id - The EPG identifier, related_media_id - The linear media ID.
        /// For other : start_date, final_date, external_ids
        /// </summary>
        [DataMember(Name = "extraParams")]
        [JsonProperty("extraParams", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("extraParams", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("extra_params")]
        public SerializableDictionary<string, KalturaStringValue> ExtraParams { get; set; }
    }
}
