// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace WebAPI.Models.Catalog
{
    /// <summary>
    /// Group by a tag or meta - according to the name that appears in the system (similar to KSQL)
    /// </summary>
    [Serializable]
    public partial class KalturaAssetMetaOrTagGroupBy : KalturaAssetGroupBy
    {
        /// <summary>
        /// Group by a tag or meta - according to the name that appears in the system (similar to KSQL)
        /// </summary>
        [DataMember(Name = "value")]
        [JsonProperty("value")]
        [XmlElement("value")]
        public string Value { get; set; }
    }
}
