// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;

namespace WebAPI.Models.Catalog
{
    [Serializable]
    public partial class KalturaRelatedFilter : KalturaBaseSearchAssetFilter
    {
        /// <summary>
        /// the ID of the asset for which to return related assets
        /// </summary>
        [DataMember(Name = "idEqual")]
        [JsonProperty("idEqual")]
        [XmlElement("idEqual", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 1)]
        public int? IdEqual { get; set; }

        /// <summary>
        /// Comma separated list of asset types to search within. 
        /// Possible values: any media type ID (according to media type IDs defined dynamically in the system).
        /// If omitted - same type as the provided asset.
        /// </summary>
        [DataMember(Name = "typeIn")]
        [JsonProperty("typeIn")]
        [XmlElement("typeIn", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public string TypeIn { get; set; }

        /// <summary>
        /// Exclude watched asset.
        /// </summary>
        [DataMember(Name = "excludeWatched")]
        [JsonProperty("excludeWatched")]
        [XmlElement("excludeWatched")]
        [ValidationException(SchemeValidationType.FILTER_SUFFIX)]
        public bool ExcludeWatched { get; set; }
    }
}
