// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;
using WebAPI.Models.General;

namespace WebAPI.Models.Catalog
{
    [Serializable]
    public partial class KalturaAssetCommentFilter : KalturaFilter<KalturaAssetCommentOrderBy>
    {
        /// <summary>
        /// Asset Id
        /// </summary>
        [DataMember(Name = "assetIdEqual")]
        [JsonProperty("assetIdEqual")]
        [XmlElement("assetIdEqual")]
        [SchemeProperty(MinInteger = 1)]
        public int AssetIdEqual { get; set; }

        /// <summary>
        /// Asset Type
        /// </summary>
        [DataMember(Name = "assetTypeEqual")]
        [JsonProperty("assetTypeEqual")]
        [XmlElement("assetTypeEqual")]
        public KalturaAssetType AssetTypeEqual { get; set; }

        public override KalturaAssetCommentOrderBy GetDefaultOrderByValue()
        {
            return KalturaAssetCommentOrderBy.CREATE_DATE_DESC;
        }
    }
}
