// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using System;

namespace WebAPI.Models.Catalog
{
    /// <summary>
    /// Different fields that can be used for grouping
    /// </summary>
    [Serializable]
    public enum KalturaGroupByField
    {
        media_type_id = 0,
        suppressed = 1,
        crid = 2,
        linear_media_id = 3,
        name = 4
    }
}
