// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Jil;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;
using WebAPI.Models.General;

namespace WebAPI.Models.Catalog
{
    /// <summary>
    /// Slim asset info
    /// </summary>
    [Serializable]
    [Obsolete]
    public partial class KalturaBaseAssetInfo : KalturaOTTObject, KalturaIAssetable
    {
        /// <summary>
        /// Unique identifier for the asset
        /// </summary>
        [DataMember(Name = "id")]
        [JsonProperty("id")]
        [XmlElement("id", IsNullable = true)]
        [SchemeProperty(IsNullable = true, ReadOnly = true)]
        public long? Id { get; set; }

        /// <summary>
        /// Identifies the asset type (EPG, Recording, Movie, TV Series, etc). 
        /// Possible values: 0 - EPG linear programs, 1 - Recording; or any asset type ID according to the asset types IDs defined in the system.
        /// </summary>
        [DataMember(Name = "type")]
        [JsonProperty("type")]
        [XmlElement("type", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public int? Type { get; set; }

        /// <summary>
        /// Asset name
        /// </summary>
        [DataMember(Name = "name")]
        [JsonProperty("name")]
        [XmlElement("name")]
        public string Name { get; set; }

        /// <summary>
        /// Asset description
        /// </summary>
        [DataMember(Name = "description")]
        [JsonProperty("description")]
        [XmlElement("description")]
        public string Description { get; set; }

        /// <summary>
        /// Collection of images details that can be used to represent this asset
        /// </summary>
        [DataMember(Name = "images")]
        [JsonProperty("images", NullValueHandling = NullValueHandling.Ignore)]
        [XmlArray("images", IsNullable = true)]
        [XmlArrayItem("item")]
        public List<KalturaMediaImage> Images { get; set; }

        /// <summary>
        /// Files
        /// </summary>
        [DataMember(Name = "mediaFiles")]
        [JsonProperty("mediaFiles", NullValueHandling = NullValueHandling.Ignore)]
        [XmlArray("mediaFiles", IsNullable = true)]
        [XmlArrayItem("item")]
        [OldStandardProperty("media_files")]
        public List<KalturaMediaFile> MediaFiles { get; set; }

        /// <summary>
        /// Collection of add-on statistical information for the media. See AssetStats model for more information
        /// </summary>
        [DataMember(Name = "stats")]
        [JsonProperty("stats", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("stats", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [JilDirective(true)]
        [Obsolete]
        public KalturaAssetStatistics Statistics { get; set; }
    }
}
