// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;
using WebAPI.Models.General;

namespace WebAPI.Models.Notification
{
    /// <summary>
    /// order announcements
    /// </summary>
    [Serializable]
    public partial class KalturaAnnouncementFilter : KalturaFilter<KalturaAnnouncementOrderBy>
    {
        /// <summary>
        /// A list of comma separated announcement ids.
        /// </summary>
        [DataMember(Name = "idIn")]
        [JsonProperty("idIn")]
        [XmlElement("idIn", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public string IdIn { get; set; }

        public override KalturaAnnouncementOrderBy GetDefaultOrderByValue()
        {
            return KalturaAnnouncementOrderBy.NONE;
        }
    }
}
