// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Models.General;

namespace WebAPI.Models.Notification
{
    /// <summary>
    /// List of message announcements from DB.
    /// </summary>
    [DataContract(Name = "KalturaAnnouncementListResponse", Namespace = "")]
    [XmlRoot("KalturaAnnouncementListResponse")]
    [Serializable]
    public partial class KalturaAnnouncementListResponse : KalturaListResponse
    {
        /// <summary>
        /// Announcements
        /// </summary>
        [DataMember(Name = "objects")]
        [JsonProperty("objects")]
        [XmlArray("objects", IsNullable = true)]
        [XmlArrayItem("item")]
        public List<KalturaAnnouncement> Announcements { get; set; }
    }
}
