{{- $chartName := .Chart.Name -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $envTag := .Values.env.tag -}}
{{- $envRepository := .Values.env.repository -}}


{{- range .Values.handlers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    app.kubernetes.io/name: {{ .Name }}
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Name }}
      app.kubernetes.io/instance: {{ $releaseName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Name }}
        app.kubernetes.io/instance: {{ $releaseName }}
    spec:
      containers:
        - name: {{ .Name }}
          image: "{{ $envRepository }}/{{ $envTag }}-{{ $chartName }}:{{ $chartAppVersion }}"
          imagePullPolicy: Always
          env:
            - name: RUN_TASK
              value: {{ .task }}
            - name: TCM_SECTION
              value: {{ $envTag }}
            - name: TCM_URL
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.url
            - name: TCM_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appId
            - name: TCM_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appSecret
      strategy:
        type: RollingUpdate
        maxUnavailable: 1
      nodeSelector:
        kaltura.role: core

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ .Name }}
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
{{- end }}