{{- range .Values.handlers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    app.kubernetes.io/name: {{ .Name }}
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Name }}
          image: "{{ required "Value env.repository is required!" .Values.env.repository }}/{{ required "Value env.tag is required!" .Values.env.tag }}-{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: RUN_TASK
              value: {{ .task }}
            - name: TCM_SECTION
              value: {{ .Values.env.tag }}
            - name: TCM_URL
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.url
            - name: TCM_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appId
            - name: TCM_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appSecret
      strategy:
        type: RollingUpdate
        maxUnavailable: 1
      nodeSelector:
        kaltura.role: core

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Name }}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Name }}
  minReplicas: 2
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
{{- end }}