//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdapterControllers.PlaybackAdapter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdapterStatus", Namespace="http://schemas.datacontract.org/2004/07/PGAdapterCommon.Models")]
    [System.SerializableAttribute()]
    public partial class AdapterStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdapterPlaybackContextOptions", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class AdapterPlaybackContextOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AdapterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.AdapterPlaybackContext PlaybackContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AdapterId {
            get {
                return this.AdapterIdField;
            }
            set {
                if ((this.AdapterIdField.Equals(value) != true)) {
                    this.AdapterIdField = value;
                    this.RaisePropertyChanged("AdapterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.AdapterPlaybackContext PlaybackContext {
            get {
                return this.PlaybackContextField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaybackContextField, value) != true)) {
                    this.PlaybackContextField = value;
                    this.RaisePropertyChanged("PlaybackContext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Udid {
            get {
                return this.UdidField;
            }
            set {
                if ((object.ReferenceEquals(this.UdidField, value) != true)) {
                    this.UdidField = value;
                    this.RaisePropertyChanged("Udid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdapterPlaybackContext", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class AdapterPlaybackContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.RuleAction[] ActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.AccessControlMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.CaptionPlaybackPluginData[] PlaybackCaptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.PlaybackPluginData[] PluginsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.PlaybackSource[] SourcesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.RuleAction[] Actions {
            get {
                return this.ActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionsField, value) != true)) {
                    this.ActionsField = value;
                    this.RaisePropertyChanged("Actions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.AccessControlMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.CaptionPlaybackPluginData[] PlaybackCaptions {
            get {
                return this.PlaybackCaptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaybackCaptionsField, value) != true)) {
                    this.PlaybackCaptionsField = value;
                    this.RaisePropertyChanged("PlaybackCaptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.PlaybackPluginData[] Plugins {
            get {
                return this.PluginsField;
            }
            set {
                if ((object.ReferenceEquals(this.PluginsField, value) != true)) {
                    this.PluginsField = value;
                    this.RaisePropertyChanged("Plugins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.PlaybackSource[] Sources {
            get {
                return this.SourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.SourcesField, value) != true)) {
                    this.SourcesField = value;
                    this.RaisePropertyChanged("Sources");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleAction", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class RuleAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.RuleActionType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.RuleActionType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessControlMessage", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class AccessControlMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptionPlaybackPluginData", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class CaptionPlaybackPluginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaybackPluginData", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.BumperPlaybackPluginData))]
    public partial class PlaybackPluginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaybackSource", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class PlaybackSource : AdapterControllers.PlaybackAdapter.MediaFile {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.DrmPlaybackPluginData[] DrmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTokenizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProtocolsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.DrmPlaybackPluginData[] Drm {
            get {
                return this.DrmField;
            }
            set {
                if ((object.ReferenceEquals(this.DrmField, value) != true)) {
                    this.DrmField = value;
                    this.RaisePropertyChanged("Drm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTokenized {
            get {
                return this.IsTokenizedField;
            }
            set {
                if ((this.IsTokenizedField.Equals(value) != true)) {
                    this.IsTokenizedField = value;
                    this.RaisePropertyChanged("IsTokenized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Protocols {
            get {
                return this.ProtocolsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProtocolsField, value) != true)) {
                    this.ProtocolsField = value;
                    this.RaisePropertyChanged("Protocols");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleActionType", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    public enum RuleActionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BLOCK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        START_DATE_OFFSET = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        END_DATE_OFFSET = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_BLOCK = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALLOW_PLAYBACK = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BLOCK_PLAYBACK = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        APPLY_DISCOUNT_MODULE = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        APPLY_PLAYBACK_ADAPTER = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BumperPlaybackPluginData", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class BumperPlaybackPluginData : AdapterControllers.PlaybackAdapter.PlaybackPluginData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreamerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreamerType {
            get {
                return this.StreamerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StreamerTypeField, value) != true)) {
                    this.StreamerTypeField = value;
                    this.RaisePropertyChanged("StreamerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetFile", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.MediaFile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.PlaybackSource))]
    public partial class AssetFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaFile", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.PlaybackSource))]
    public partial class MediaFile : AdapterControllers.PlaybackAdapter.AssetFile {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltStreamingCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AlternativeCdnAdapaterProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AssetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CatalogEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CdnAdapaterProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalStoreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDefaultLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputProtecationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltExternalId {
            get {
                return this.AltExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AltExternalIdField, value) != true)) {
                    this.AltExternalIdField = value;
                    this.RaisePropertyChanged("AltExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltStreamingCode {
            get {
                return this.AltStreamingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AltStreamingCodeField, value) != true)) {
                    this.AltStreamingCodeField = value;
                    this.RaisePropertyChanged("AltStreamingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AlternativeCdnAdapaterProfileId {
            get {
                return this.AlternativeCdnAdapaterProfileIdField;
            }
            set {
                if ((this.AlternativeCdnAdapaterProfileIdField.Equals(value) != true)) {
                    this.AlternativeCdnAdapaterProfileIdField = value;
                    this.RaisePropertyChanged("AlternativeCdnAdapaterProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AssetId {
            get {
                return this.AssetIdField;
            }
            set {
                if ((this.AssetIdField.Equals(value) != true)) {
                    this.AssetIdField = value;
                    this.RaisePropertyChanged("AssetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CatalogEndDate {
            get {
                return this.CatalogEndDateField;
            }
            set {
                if ((this.CatalogEndDateField.Equals(value) != true)) {
                    this.CatalogEndDateField = value;
                    this.RaisePropertyChanged("CatalogEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CdnAdapaterProfileId {
            get {
                return this.CdnAdapaterProfileIdField;
            }
            set {
                if ((this.CdnAdapaterProfileIdField.Equals(value) != true)) {
                    this.CdnAdapaterProfileIdField = value;
                    this.RaisePropertyChanged("CdnAdapaterProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalStoreId {
            get {
                return this.ExternalStoreIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalStoreIdField, value) != true)) {
                    this.ExternalStoreIdField = value;
                    this.RaisePropertyChanged("ExternalStoreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDefaultLanguage {
            get {
                return this.IsDefaultLanguageField;
            }
            set {
                if ((this.IsDefaultLanguageField.Equals(value) != true)) {
                    this.IsDefaultLanguageField = value;
                    this.RaisePropertyChanged("IsDefaultLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderNum {
            get {
                return this.OrderNumField;
            }
            set {
                if ((this.OrderNumField.Equals(value) != true)) {
                    this.OrderNumField = value;
                    this.RaisePropertyChanged("OrderNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputProtecationLevel {
            get {
                return this.OutputProtecationLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputProtecationLevelField, value) != true)) {
                    this.OutputProtecationLevelField = value;
                    this.RaisePropertyChanged("OutputProtecationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrmPlaybackPluginData", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.CustomDrmPlaybackPluginData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.FairPlayPlaybackPluginData))]
    public partial class DrmPlaybackPluginData : AdapterControllers.PlaybackAdapter.PluginData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.DrmSchemeName SchemeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseURL {
            get {
                return this.LicenseURLField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseURLField, value) != true)) {
                    this.LicenseURLField = value;
                    this.RaisePropertyChanged("LicenseURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.DrmSchemeName Scheme {
            get {
                return this.SchemeField;
            }
            set {
                if ((this.SchemeField.Equals(value) != true)) {
                    this.SchemeField = value;
                    this.RaisePropertyChanged("Scheme");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PluginData", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.DrmPlaybackPluginData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.CustomDrmPlaybackPluginData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdapterControllers.PlaybackAdapter.FairPlayPlaybackPluginData))]
    public partial class PluginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomDrmPlaybackPluginData", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class CustomDrmPlaybackPluginData : AdapterControllers.PlaybackAdapter.DrmPlaybackPluginData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FairPlayPlaybackPluginData", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class FairPlayPlaybackPluginData : AdapterControllers.PlaybackAdapter.DrmPlaybackPluginData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Certificate {
            get {
                return this.CertificateField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateField, value) != true)) {
                    this.CertificateField = value;
                    this.RaisePropertyChanged("Certificate");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrmSchemeName", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    public enum DrmSchemeName : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYREADY_CENC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WIDEVINE_CENC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAIRPLAY = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WIDEVINE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLAYREADY = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOM_DRM = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaybackAdapterResponse", Namespace="http://schemas.datacontract.org/2004/07/PlaybackAdapter")]
    [System.SerializableAttribute()]
    public partial class PlaybackAdapterResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.AdapterPlaybackContext PlaybackContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdapterControllers.PlaybackAdapter.AdapterStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.AdapterPlaybackContext PlaybackContext {
            get {
                return this.PlaybackContextField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaybackContextField, value) != true)) {
                    this.PlaybackContextField = value;
                    this.RaisePropertyChanged("PlaybackContext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdapterControllers.PlaybackAdapter.AdapterStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlaybackAdapter.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetConfiguration", ReplyAction="http://tempuri.org/IService/SetConfigurationResponse")]
        AdapterControllers.PlaybackAdapter.AdapterStatus SetConfiguration(long adapterId, string settings, int partnerId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetConfiguration", ReplyAction="http://tempuri.org/IService/SetConfigurationResponse")]
        System.Threading.Tasks.Task<AdapterControllers.PlaybackAdapter.AdapterStatus> SetConfigurationAsync(long adapterId, string settings, int partnerId, long timeStamp, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPlaybackContext", ReplyAction="http://tempuri.org/IService/GetPlaybackContextResponse")]
        AdapterControllers.PlaybackAdapter.PlaybackAdapterResponse GetPlaybackContext(AdapterControllers.PlaybackAdapter.AdapterPlaybackContextOptions adapterPlaybackContextOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPlaybackContext", ReplyAction="http://tempuri.org/IService/GetPlaybackContextResponse")]
        System.Threading.Tasks.Task<AdapterControllers.PlaybackAdapter.PlaybackAdapterResponse> GetPlaybackContextAsync(AdapterControllers.PlaybackAdapter.AdapterPlaybackContextOptions adapterPlaybackContextOptions);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : AdapterControllers.PlaybackAdapter.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<AdapterControllers.PlaybackAdapter.IService>, AdapterControllers.PlaybackAdapter.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdapterControllers.PlaybackAdapter.AdapterStatus SetConfiguration(long adapterId, string settings, int partnerId, long timeStamp, string signature) {
            return base.Channel.SetConfiguration(adapterId, settings, partnerId, timeStamp, signature);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.PlaybackAdapter.AdapterStatus> SetConfigurationAsync(long adapterId, string settings, int partnerId, long timeStamp, string signature) {
            return base.Channel.SetConfigurationAsync(adapterId, settings, partnerId, timeStamp, signature);
        }
        
        public AdapterControllers.PlaybackAdapter.PlaybackAdapterResponse GetPlaybackContext(AdapterControllers.PlaybackAdapter.AdapterPlaybackContextOptions adapterPlaybackContextOptions) {
            return base.Channel.GetPlaybackContext(adapterPlaybackContextOptions);
        }
        
        public System.Threading.Tasks.Task<AdapterControllers.PlaybackAdapter.PlaybackAdapterResponse> GetPlaybackContextAsync(AdapterControllers.PlaybackAdapter.AdapterPlaybackContextOptions adapterPlaybackContextOptions) {
            return base.Channel.GetPlaybackContextAsync(adapterPlaybackContextOptions);
        }
    }
}
