//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APILogic.AdyenRecAPI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisableRequest", Namespace="http://recurring.services.adyen.com")]
    public partial class DisableRequest : object
    {
        
        private string contractField;
        
        private string merchantAccountField;
        
        private string recurringDetailReferenceField;
        
        private string shopperReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contract
        {
            get
            {
                return this.contractField;
            }
            set
            {
                this.contractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount
        {
            get
            {
                return this.merchantAccountField;
            }
            set
            {
                this.merchantAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailReference
        {
            get
            {
                return this.recurringDetailReferenceField;
            }
            set
            {
                this.recurringDetailReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference
        {
            get
            {
                return this.shopperReferenceField;
            }
            set
            {
                this.shopperReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisableResult", Namespace="http://recurring.services.adyen.com")]
    public partial class DisableResult : object
    {
        
        private string responseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://common.services.adyen.com")]
    public partial class ServiceException : object
    {
        
        private System.Nullable<APILogic.AdyenRecAPI.Error> errorField;
        
        private System.Nullable<APILogic.AdyenRecAPI.Type> typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<APILogic.AdyenRecAPI.Error> error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<APILogic.AdyenRecAPI.Type> type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://common.services.adyen.com")]
    public enum Error : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAllowed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAmountSpecified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToDetermineVariant = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMerchantAccount = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestMissing = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnableToProcess = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentDetailsAreNotSupported = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://common.services.adyen.com")]
    public enum Type : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @internal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        validation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        security = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        configuration = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringDetailsRequest", Namespace="http://recurring.services.adyen.com")]
    public partial class RecurringDetailsRequest : object
    {
        
        private string merchantAccountField;
        
        private APILogic.AdyenRecAPI.Recurring recurringField;
        
        private string shopperReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount
        {
            get
            {
                return this.merchantAccountField;
            }
            set
            {
                this.merchantAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Recurring recurring
        {
            get
            {
                return this.recurringField;
            }
            set
            {
                this.recurringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference
        {
            get
            {
                return this.shopperReferenceField;
            }
            set
            {
                this.shopperReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recurring", Namespace="http://payment.services.adyen.com")]
    public partial class Recurring : object
    {
        
        private string contractField;
        
        private string recurringDetailNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contract
        {
            get
            {
                return this.contractField;
            }
            set
            {
                this.contractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailName
        {
            get
            {
                return this.recurringDetailNameField;
            }
            set
            {
                this.recurringDetailNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringDetailsResult", Namespace="http://recurring.services.adyen.com")]
    public partial class RecurringDetailsResult : object
    {
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private APILogic.AdyenRecAPI.RecurringDetail[] detailsField;
        
        private string lastKnownShopperEmailField;
        
        private string shopperReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> creationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.RecurringDetail[] details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastKnownShopperEmail
        {
            get
            {
                return this.lastKnownShopperEmailField;
            }
            set
            {
                this.lastKnownShopperEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference
        {
            get
            {
                return this.shopperReferenceField;
            }
            set
            {
                this.shopperReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringDetail", Namespace="http://recurring.services.adyen.com")]
    public partial class RecurringDetail : object
    {
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap additionalDataField;
        
        private string aliasField;
        
        private string aliasTypeField;
        
        private APILogic.AdyenRecAPI.BankAccount bankField;
        
        private APILogic.AdyenRecAPI.Address billingAddressField;
        
        private APILogic.AdyenRecAPI.Card cardField;
        
        private APILogic.AdyenRecAPI.ArrayOfString contractTypesField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private APILogic.AdyenRecAPI.ELV elvField;
        
        private string firstPspReferenceField;
        
        private string nameField;
        
        private string paymentMethodVariantField;
        
        private string recurringDetailReferenceField;
        
        private APILogic.AdyenRecAPI.Name shopperNameField;
        
        private string socialSecurityNumberField;
        
        private APILogic.AdyenRecAPI.TokenDetails tokenDetailsField;
        
        private string variantField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aliasType
        {
            get
            {
                return this.aliasTypeField;
            }
            set
            {
                this.aliasTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.BankAccount bank
        {
            get
            {
                return this.bankField;
            }
            set
            {
                this.bankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Address billingAddress
        {
            get
            {
                return this.billingAddressField;
            }
            set
            {
                this.billingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Card card
        {
            get
            {
                return this.cardField;
            }
            set
            {
                this.cardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.ArrayOfString contractTypes
        {
            get
            {
                return this.contractTypesField;
            }
            set
            {
                this.contractTypesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> creationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.ELV elv
        {
            get
            {
                return this.elvField;
            }
            set
            {
                this.elvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstPspReference
        {
            get
            {
                return this.firstPspReferenceField;
            }
            set
            {
                this.firstPspReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentMethodVariant
        {
            get
            {
                return this.paymentMethodVariantField;
            }
            set
            {
                this.paymentMethodVariantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailReference
        {
            get
            {
                return this.recurringDetailReferenceField;
            }
            set
            {
                this.recurringDetailReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Name shopperName
        {
            get
            {
                return this.shopperNameField;
            }
            set
            {
                this.shopperNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string socialSecurityNumber
        {
            get
            {
                return this.socialSecurityNumberField;
            }
            set
            {
                this.socialSecurityNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.TokenDetails tokenDetails
        {
            get
            {
                return this.tokenDetailsField;
            }
            set
            {
                this.tokenDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string variant
        {
            get
            {
                return this.variantField;
            }
            set
            {
                this.variantField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://payment.services.adyen.com")]
    public partial class BankAccount : object
    {
        
        private string bankAccountNumberField;
        
        private string bankLocationIdField;
        
        private string bankNameField;
        
        private string bicField;
        
        private string countryCodeField;
        
        private string ibanField;
        
        private string ownerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankAccountNumber
        {
            get
            {
                return this.bankAccountNumberField;
            }
            set
            {
                this.bankAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankLocationId
        {
            get
            {
                return this.bankLocationIdField;
            }
            set
            {
                this.bankLocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankName
        {
            get
            {
                return this.bankNameField;
            }
            set
            {
                this.bankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bic
        {
            get
            {
                return this.bicField;
            }
            set
            {
                this.bicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iban
        {
            get
            {
                return this.ibanField;
            }
            set
            {
                this.ibanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ownerName
        {
            get
            {
                return this.ownerNameField;
            }
            set
            {
                this.ownerNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://common.services.adyen.com")]
    public partial class Address : object
    {
        
        private string cityField;
        
        private string countryField;
        
        private string houseNumberOrNameField;
        
        private string postalCodeField;
        
        private string stateOrProvinceField;
        
        private string streetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string houseNumberOrName
        {
            get
            {
                return this.houseNumberOrNameField;
            }
            set
            {
                this.houseNumberOrNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateOrProvince
        {
            get
            {
                return this.stateOrProvinceField;
            }
            set
            {
                this.stateOrProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://payment.services.adyen.com")]
    public partial class Card : object
    {
        
        private APILogic.AdyenRecAPI.Address billingAddressField;
        
        private string cvcField;
        
        private string expiryMonthField;
        
        private string expiryYearField;
        
        private string holderNameField;
        
        private string issueNumberField;
        
        private string numberField;
        
        private string startMonthField;
        
        private string startYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Address billingAddress
        {
            get
            {
                return this.billingAddressField;
            }
            set
            {
                this.billingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cvc
        {
            get
            {
                return this.cvcField;
            }
            set
            {
                this.cvcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string expiryMonth
        {
            get
            {
                return this.expiryMonthField;
            }
            set
            {
                this.expiryMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string expiryYear
        {
            get
            {
                return this.expiryYearField;
            }
            set
            {
                this.expiryYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string holderName
        {
            get
            {
                return this.holderNameField;
            }
            set
            {
                this.holderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string issueNumber
        {
            get
            {
                return this.issueNumberField;
            }
            set
            {
                this.issueNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startMonth
        {
            get
            {
                return this.startMonthField;
            }
            set
            {
                this.startMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startYear
        {
            get
            {
                return this.startYearField;
            }
            set
            {
                this.startYearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELV", Namespace="http://payment.services.adyen.com")]
    public partial class ELV : object
    {
        
        private string accountHolderNameField;
        
        private string bankAccountNumberField;
        
        private string bankLocationField;
        
        private string bankLocationIdField;
        
        private string bankNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountHolderName
        {
            get
            {
                return this.accountHolderNameField;
            }
            set
            {
                this.accountHolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankAccountNumber
        {
            get
            {
                return this.bankAccountNumberField;
            }
            set
            {
                this.bankAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankLocation
        {
            get
            {
                return this.bankLocationField;
            }
            set
            {
                this.bankLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankLocationId
        {
            get
            {
                return this.bankLocationIdField;
            }
            set
            {
                this.bankLocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankName
        {
            get
            {
                return this.bankNameField;
            }
            set
            {
                this.bankNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Name", Namespace="http://common.services.adyen.com")]
    public partial class Name : object
    {
        
        private string firstNameField;
        
        private System.Nullable<APILogic.AdyenRecAPI.Gender> genderField;
        
        private string infixField;
        
        private string lastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<APILogic.AdyenRecAPI.Gender> gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string infix
        {
            get
            {
                return this.infixField;
            }
            set
            {
                this.infixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenDetails", Namespace="http://payment.services.adyen.com")]
    public partial class TokenDetails : object
    {
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap tokenDataField;
        
        private string tokenDataTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap tokenData
        {
            get
            {
                return this.tokenDataField;
            }
            set
            {
                this.tokenDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tokenDataType
        {
            get
            {
                return this.tokenDataTypeField;
            }
            set
            {
                this.tokenDataTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="anyType2anyTypeMap", Namespace="http://recurring.services.adyen.com", ItemName="entry")]
    public class anyType2anyTypeMap : System.Collections.Generic.List<APILogic.AdyenRecAPI.entry>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://recurring.services.adyen.com", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entry", Namespace="http://recurring.services.adyen.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.DisableRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.DisableResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.RecurringDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.RecurringDetailsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.RecurringDetailsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.ScheduleAccountUpdaterRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.ScheduleAccountUpdaterResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.StoreTokenRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.StoreTokenResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.TokenDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.TokenLookupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.TokenLookupResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.RecurringDetail[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.TokenDetail[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.anyType2anyTypeMap))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.Address))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.Name))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.Gender))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.Error))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.Type))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.BankAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.Card))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.ELV))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.Recurring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(APILogic.AdyenRecAPI.TokenDetails))]
    public partial class entry : object
    {
        
        private object keyField;
        
        private object valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleAccountUpdaterRequest", Namespace="http://recurring.services.adyen.com")]
    public partial class ScheduleAccountUpdaterRequest : object
    {
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap additionalDataField;
        
        private APILogic.AdyenRecAPI.Card cardField;
        
        private string merchantAccountField;
        
        private string referenceField;
        
        private string selectedRecurringDetailReferenceField;
        
        private string shopperReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Card card
        {
            get
            {
                return this.cardField;
            }
            set
            {
                this.cardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string merchantAccount
        {
            get
            {
                return this.merchantAccountField;
            }
            set
            {
                this.merchantAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string selectedRecurringDetailReference
        {
            get
            {
                return this.selectedRecurringDetailReferenceField;
            }
            set
            {
                this.selectedRecurringDetailReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference
        {
            get
            {
                return this.shopperReferenceField;
            }
            set
            {
                this.shopperReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleAccountUpdaterResult", Namespace="http://recurring.services.adyen.com")]
    public partial class ScheduleAccountUpdaterResult : object
    {
        
        private string pspReferenceField;
        
        private string resultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pspReference
        {
            get
            {
                return this.pspReferenceField;
            }
            set
            {
                this.pspReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreTokenRequest", Namespace="http://recurring.services.adyen.com")]
    public partial class StoreTokenRequest : object
    {
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap additionalDataField;
        
        private APILogic.AdyenRecAPI.BankAccount bankField;
        
        private APILogic.AdyenRecAPI.Card cardField;
        
        private APILogic.AdyenRecAPI.ELV elvField;
        
        private string merchantAccountField;
        
        private string nameField;
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap paramsField;
        
        private string pspEchoDataField;
        
        private APILogic.AdyenRecAPI.Recurring recurringField;
        
        private string returnUrlField;
        
        private string selectedBrandField;
        
        private string shopperEmailField;
        
        private string shopperIPField;
        
        private string shopperReferenceField;
        
        private string shopperStatementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.BankAccount bank
        {
            get
            {
                return this.bankField;
            }
            set
            {
                this.bankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Card card
        {
            get
            {
                return this.cardField;
            }
            set
            {
                this.cardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.ELV elv
        {
            get
            {
                return this.elvField;
            }
            set
            {
                this.elvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount
        {
            get
            {
                return this.merchantAccountField;
            }
            set
            {
                this.merchantAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap @params
        {
            get
            {
                return this.paramsField;
            }
            set
            {
                this.paramsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pspEchoData
        {
            get
            {
                return this.pspEchoDataField;
            }
            set
            {
                this.pspEchoDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Recurring recurring
        {
            get
            {
                return this.recurringField;
            }
            set
            {
                this.recurringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string returnUrl
        {
            get
            {
                return this.returnUrlField;
            }
            set
            {
                this.returnUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string selectedBrand
        {
            get
            {
                return this.selectedBrandField;
            }
            set
            {
                this.selectedBrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperEmail
        {
            get
            {
                return this.shopperEmailField;
            }
            set
            {
                this.shopperEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperIP
        {
            get
            {
                return this.shopperIPField;
            }
            set
            {
                this.shopperIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference
        {
            get
            {
                return this.shopperReferenceField;
            }
            set
            {
                this.shopperReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperStatement
        {
            get
            {
                return this.shopperStatementField;
            }
            set
            {
                this.shopperStatementField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreTokenResult", Namespace="http://recurring.services.adyen.com")]
    public partial class StoreTokenResult : object
    {
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap additionalDataField;
        
        private string aliasField;
        
        private string aliasTypeField;
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap paramsField;
        
        private string pspEchoDataField;
        
        private string pspReferenceField;
        
        private string recurringDetailReferenceField;
        
        private string redirectTypeField;
        
        private string redirectUrlField;
        
        private string resultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aliasType
        {
            get
            {
                return this.aliasTypeField;
            }
            set
            {
                this.aliasTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap @params
        {
            get
            {
                return this.paramsField;
            }
            set
            {
                this.paramsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pspEchoData
        {
            get
            {
                return this.pspEchoDataField;
            }
            set
            {
                this.pspEchoDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pspReference
        {
            get
            {
                return this.pspReferenceField;
            }
            set
            {
                this.pspReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recurringDetailReference
        {
            get
            {
                return this.recurringDetailReferenceField;
            }
            set
            {
                this.recurringDetailReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string redirectType
        {
            get
            {
                return this.redirectTypeField;
            }
            set
            {
                this.redirectTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string redirectUrl
        {
            get
            {
                return this.redirectUrlField;
            }
            set
            {
                this.redirectUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenDetail", Namespace="http://recurring.services.adyen.com")]
    public partial class TokenDetail : object
    {
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private string lastKnownShopperEmailField;
        
        private string shopperReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> creationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastKnownShopperEmail
        {
            get
            {
                return this.lastKnownShopperEmailField;
            }
            set
            {
                this.lastKnownShopperEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shopperReference
        {
            get
            {
                return this.shopperReferenceField;
            }
            set
            {
                this.shopperReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenLookupRequest", Namespace="http://recurring.services.adyen.com")]
    public partial class TokenLookupRequest : object
    {
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap additionalDataField;
        
        private APILogic.AdyenRecAPI.BankAccount bankField;
        
        private APILogic.AdyenRecAPI.Card cardField;
        
        private APILogic.AdyenRecAPI.ELV elvField;
        
        private string merchantAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.BankAccount bank
        {
            get
            {
                return this.bankField;
            }
            set
            {
                this.bankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.Card card
        {
            get
            {
                return this.cardField;
            }
            set
            {
                this.cardField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.ELV elv
        {
            get
            {
                return this.elvField;
            }
            set
            {
                this.elvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string merchantAccount
        {
            get
            {
                return this.merchantAccountField;
            }
            set
            {
                this.merchantAccountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenLookupResult", Namespace="http://recurring.services.adyen.com")]
    public partial class TokenLookupResult : object
    {
        
        private APILogic.AdyenRecAPI.anyType2anyTypeMap additionalDataField;
        
        private string pspReferenceField;
        
        private APILogic.AdyenRecAPI.TokenDetail[] tokensField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.anyType2anyTypeMap additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pspReference
        {
            get
            {
                return this.pspReferenceField;
            }
            set
            {
                this.pspReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APILogic.AdyenRecAPI.TokenDetail[] tokens
        {
            get
            {
                return this.tokensField;
            }
            set
            {
                this.tokensField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://common.services.adyen.com")]
    public enum Gender : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MALE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FEMALE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://recurring.services.adyen.com", ConfigurationName="APILogic.AdyenRecAPI.RecurringPortType")]
    public interface RecurringPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(APILogic.AdyenRecAPI.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<APILogic.AdyenRecAPI.DisableResult> disableAsync(APILogic.AdyenRecAPI.DisableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(APILogic.AdyenRecAPI.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<APILogic.AdyenRecAPI.RecurringDetailsResult> listRecurringDetailsAsync(APILogic.AdyenRecAPI.RecurringDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(APILogic.AdyenRecAPI.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<APILogic.AdyenRecAPI.StoreTokenResult> prepareStoreTokenAsync(APILogic.AdyenRecAPI.StoreTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(APILogic.AdyenRecAPI.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<APILogic.AdyenRecAPI.ScheduleAccountUpdaterResult> scheduleAccountUpdaterAsync(APILogic.AdyenRecAPI.ScheduleAccountUpdaterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(APILogic.AdyenRecAPI.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<APILogic.AdyenRecAPI.StoreTokenResult> storeTokenAsync(APILogic.AdyenRecAPI.StoreTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(APILogic.AdyenRecAPI.ServiceException), Action="", Name="ServiceException")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<APILogic.AdyenRecAPI.TokenLookupResult> tokenLookupAsync(APILogic.AdyenRecAPI.TokenLookupRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface RecurringPortTypeChannel : APILogic.AdyenRecAPI.RecurringPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class RecurringPortTypeClient : System.ServiceModel.ClientBase<APILogic.AdyenRecAPI.RecurringPortType>, APILogic.AdyenRecAPI.RecurringPortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecurringPortTypeClient() : 
                base(RecurringPortTypeClient.GetDefaultBinding(), RecurringPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RecurringHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecurringPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(RecurringPortTypeClient.GetBindingForEndpoint(endpointConfiguration), RecurringPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecurringPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecurringPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecurringPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecurringPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecurringPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<APILogic.AdyenRecAPI.DisableResult> disableAsync(APILogic.AdyenRecAPI.DisableRequest request)
        {
            return base.Channel.disableAsync(request);
        }
        
        public System.Threading.Tasks.Task<APILogic.AdyenRecAPI.RecurringDetailsResult> listRecurringDetailsAsync(APILogic.AdyenRecAPI.RecurringDetailsRequest request)
        {
            return base.Channel.listRecurringDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<APILogic.AdyenRecAPI.StoreTokenResult> prepareStoreTokenAsync(APILogic.AdyenRecAPI.StoreTokenRequest request)
        {
            return base.Channel.prepareStoreTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<APILogic.AdyenRecAPI.ScheduleAccountUpdaterResult> scheduleAccountUpdaterAsync(APILogic.AdyenRecAPI.ScheduleAccountUpdaterRequest request)
        {
            return base.Channel.scheduleAccountUpdaterAsync(request);
        }
        
        public System.Threading.Tasks.Task<APILogic.AdyenRecAPI.StoreTokenResult> storeTokenAsync(APILogic.AdyenRecAPI.StoreTokenRequest request)
        {
            return base.Channel.storeTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<APILogic.AdyenRecAPI.TokenLookupResult> tokenLookupAsync(APILogic.AdyenRecAPI.TokenLookupRequest request)
        {
            return base.Channel.tokenLookupAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecurringHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecurringHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pal-test.adyen.com/pal/servlet/soap/Recurring/V12");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RecurringPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.RecurringHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RecurringPortTypeClient.GetEndpointAddress(EndpointConfiguration.RecurringHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            RecurringHttpPort,
        }
    }
}
