using Phx.Lib.Log;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.IO;
using System.Reflection;
using System.Runtime.Serialization.Formatters.Binary;

namespace EventBus.Abstraction
{
    public class ServiceEventNameAttribute : Attribute
    {
        public string Name { get; set; }

        public ServiceEventNameAttribute(string name)
        {
            Name = name;
        }
    }

    [Serializable]
    public abstract class ServiceEvent
    {
        public ServiceEvent()
        {
            this.RequestId = KLogger.GetRequestId();
            this.EventNameOverride = null;
        }

        [JsonProperty("group_id")] public int GroupId { get; set; }

        [JsonProperty("req_id")] public string RequestId { get; set; }

        private long _UserId;

        [JsonProperty("user_id")]
        public virtual long UserId
        {
            get => _UserId;
            set => _UserId = value;
        }

        [JsonProperty("site_guid")]
        public virtual string SiteGuid
        {
            get => _UserId.ToString();
            set => _UserId = long.Parse(value);
        }


        // in some cases service events will have keys to identify the message
        // e.g when sending event via kafka every  message has a key
        [JsonIgnore] public virtual string EventKey { get; set; }

        // in some cases service events need to be re-routed from their default
        // key that is calculated by reflection and get the routing key from configuration at runtime
        [JsonIgnore] public virtual string EventNameOverride { get; set; }

        // some events are intended to be published to a dedicated per partner consumer
        // when this value is set to true the event will using dedicated partner routing convention
        [JsonIgnore] public virtual bool EventForGroupDedicatedConsumer { get; set; }

        public string GetEventName()
        {
            var eventName = EventNameOverride ?? GetEventName(this.GetType());
            return eventName;
        }

        public string GetRoutingKey()
        {
            var eventName = this.GetEventName();
            if (EventForGroupDedicatedConsumer)
            {
                return GetDedicatedPartnerRoutingKey(this.GroupId, eventName);
            }

            return eventName;
        }

        public static string GetDedicatedPartnerRoutingKey(int? partnerId, string eventName)
        {
            var partnerIdTag = partnerId.HasValue ? $"{partnerId}_" : "";
            var routingKey = $"{partnerIdTag}{eventName}";
            return routingKey;
        }

        public static string GetEventName(Type eventType)
        {
            var routingKeyOverride = eventType.GetCustomAttribute<ServiceEventNameAttribute>();
            if (routingKeyOverride != null)
            {
                return routingKeyOverride.Name;
            }


            // if no override found the routing is generated by the event type fully qulified name;
            return $"{eventType.Namespace}.{eventType.Name}";
        }

        

        public override string ToString()
        {
            try
            {
                return $"groupId {GroupId} requestId {RequestId} eventName: {GetEventName(this.GetType())}";
            }
            catch
            {
                return base.ToString();
            }
        }
    }
}