// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: WatchersChannels.xsd
// Creation Date: 11/17/2008 12:02:20 PM
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Tvinci.Data.TVMDataLoader.Protocols.WatchersChannels
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}

	[Serializable]
	public enum file_quality
	{
		[XmlEnum(Name="low")] low,
		[XmlEnum(Name="medium")] medium,
		[XmlEnum(Name="high")] high
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class channelCollection : ArrayList
	{
		public channel Add(channel obj)
		{
			base.Add(obj);
			return obj;
		}

		public channel Add()
		{
			return Add(new channel());
		}

		public void Insert(int index, channel obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(channel obj)
		{
			base.Remove(obj);
		}

		new public channel this[int index]
		{
			get { return (channel) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlRoot(ElementName="WatchersChannels",IsNullable=false),Serializable]
	public partial class WatchersChannels
	{

		[XmlElement(Type=typeof(root),ElementName="root",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public root __root;
		
		[XmlIgnore]
		public root root
		{
			get
			{
				if (__root == null) __root = new root();		
				return __root;
			}
			set {__root = value;}
		}

		[XmlElement(Type=typeof(response),ElementName="response",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public response __response;
		
		[XmlIgnore]
		public response response
		{
			get
			{
				if (__response == null) __response = new response();		
				return __response;
			}
			set {__response = value;}
		}

		public WatchersChannels()
		{
		}

		public void MakeSchemaCompliant()
		{
			root.MakeSchemaCompliant();
			response.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="root"),Serializable]
	public partial class root
	{

		[XmlElement(Type=typeof(request),ElementName="request",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public request __request;
		
		[XmlIgnore]
		public request request
		{
			get
			{
				if (__request == null) __request = new request();		
				return __request;
			}
			set {__request = value;}
		}

		[XmlElement(Type=typeof(flashvars),ElementName="flashvars",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public flashvars __flashvars;
		
		[XmlIgnore]
		public flashvars flashvars
		{
			get
			{
				if (__flashvars == null) __flashvars = new flashvars();		
				return __flashvars;
			}
			set {__flashvars = value;}
		}

		public root()
		{
		}

		public void MakeSchemaCompliant()
		{
			request.MakeSchemaCompliant();
			flashvars.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="request"),Serializable]
	public partial class request
	{

		[XmlAttribute(AttributeName="type",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __type;
		
		[XmlIgnore]
		public string type
		{ 
			get { return __type; }
			set { __type = value; }
		}

		[XmlElement(Type=typeof(watcher),ElementName="watcher",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public watcher __watcher;
		
		[XmlIgnore]
		public watcher watcher
		{
			get
			{
				if (__watcher == null) __watcher = new watcher();		
				return __watcher;
			}
			set {__watcher = value;}
		}

		public request()
		{
			type = "watcher_channels_list";
		}

		public void MakeSchemaCompliant()
		{
			watcher.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="watcher"),Serializable]
	public partial class watcher
	{

		[XmlAttribute(AttributeName="site_guid")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __site_guid;
		
		[XmlIgnore]
		public string site_guid
		{ 
			get { return __site_guid; }
			set { __site_guid = value; }
		}

		public watcher()
		{
			site_guid = "false";
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="flashvars"),Serializable]
	public partial class flashvars
	{

		[XmlAttribute(AttributeName="player_un")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __player_un;
		
		[XmlIgnore]
		public string player_un
		{ 
			get { return __player_un; }
			set { __player_un = value; }
		}

		[XmlAttribute(AttributeName="player_pass")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __player_pass;
		
		[XmlIgnore]
		public string player_pass
		{ 
			get { return __player_pass; }
			set { __player_pass = value; }
		}

		[XmlAttribute(AttributeName="pic_size1")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __pic_size1;
		
		[XmlIgnore]
		public string pic_size1
		{ 
			get { return __pic_size1; }
			set { __pic_size1 = value; }
		}

		[XmlAttribute(AttributeName="lang")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __lang;
		
		[XmlIgnore]
		public string lang
		{ 
			get { return __lang; }
			set { __lang = value; }
		}

		[XmlAttribute(AttributeName="no_cache")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __no_cache;
		
		[XmlIgnore]
		public string no_cache
		{ 
			get { return __no_cache; }
			set { __no_cache = value; }
		}

		[XmlAttribute(AttributeName="timer")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __timer;
		
		[XmlIgnore]
		public string timer
		{ 
			get { return __timer; }
			set { __timer = value; }
		}

		[XmlAttribute(AttributeName="file_format")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __file_format;
		
		[XmlIgnore]
		public string file_format
		{ 
			get { return __file_format; }
			set { __file_format = value; }
		}

		[XmlAttribute(AttributeName="file_quality")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public file_quality __file_quality;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __file_qualitySpecified;
		
		[XmlIgnore]
		public file_quality file_quality
		{ 
			get { return __file_quality; }
			set { __file_quality = value; __file_qualitySpecified = true; }
		}

		public flashvars()
		{
			player_un = string.Empty;
			player_pass = string.Empty;
			pic_size1 = string.Empty;
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="response"),Serializable]
	public partial class response
	{

		[XmlAttribute(AttributeName="type")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __type;
		
		[XmlIgnore]
		public string type
		{ 
			get { return __type; }
			set { __type = value; }
		}

		[XmlElement(Type=typeof(responsewatcher),ElementName="watcher",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public responsewatcher __watcher;
		
		[XmlIgnore]
		public responsewatcher watcher
		{
			get
			{
				if (__watcher == null) __watcher = new responsewatcher();		
				return __watcher;
			}
			set {__watcher = value;}
		}

		public response()
		{
		}

		public void MakeSchemaCompliant()
		{
			watcher.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="responsewatcher"),Serializable]
	public partial class responsewatcher
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return channelCollection.GetEnumerator();
		}

		public channel Add(channel obj)
		{
			return channelCollection.Add(obj);
		}

		[XmlIgnore]
		public channel this[int index]
		{
			get { return (channel) channelCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return channelCollection.Count; }
        }

        public void Clear()
		{
			channelCollection.Clear();
        }

		public channel Remove(int index) 
		{ 
            channel obj = channelCollection[index];
            channelCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            channelCollection.Remove(obj);
        }

		[XmlAttribute(AttributeName="id")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __id;
		
		[XmlIgnore]
		public string id
		{ 
			get { return __id; }
			set { __id = value; }
		}

		[XmlAttribute(AttributeName="guid")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __guid;
		
		[XmlIgnore]
		public string guid
		{ 
			get { return __guid; }
			set { __guid = value; }
		}

		[XmlAttribute(AttributeName="site_guid")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __site_guid;
		
		[XmlIgnore]
		public string site_guid
		{ 
			get { return __site_guid; }
			set { __site_guid = value; }
		}

		[XmlElement(Type=typeof(channel),ElementName="channel",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public channelCollection __channelCollection;
		
		[XmlIgnore]
		public channelCollection channelCollection
		{
			get
			{
				if (__channelCollection == null) __channelCollection = new channelCollection();
				return __channelCollection;
			}
			set {__channelCollection = value;}
		}

		public responsewatcher()
		{
		}

		public void MakeSchemaCompliant()
		{
			if (channelCollection.Count == 0)
			{
				channel _c = channelCollection.Add();
				_c.MakeSchemaCompliant();
			}
			else foreach (channel _c in channelCollection) _c.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="channel"),Serializable]
	public partial class channel
	{

		[XmlAttribute(AttributeName="id",DataType="long")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public long __id;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __idSpecified;
		
		[XmlIgnore]
		public long id
		{ 
			get { return __id; }
			set { __id = value; __idSpecified = true; }
		}

		[XmlAttribute(AttributeName="pic_size1",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __pic_size1;
		
		[XmlIgnore]
		public string pic_size1
		{ 
			get { return __pic_size1; }
			set { __pic_size1 = value; }
		}

		[XmlAttribute(AttributeName="title",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __title;
		
		[XmlIgnore]
		public string title
		{ 
			get { return __title; }
			set { __title = value; }
		}

		[XmlAttribute(AttributeName="media_count",DataType="long")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public long __media_count;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __media_countSpecified;
		
		[XmlIgnore]
		public long media_count
		{ 
			get { return __media_count; }
			set { __media_count = value; __media_countSpecified = true; }
		}

		public channel()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}
}
