//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace TVPApiModule.yes.tvinci.ITProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddDeviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEntitlementsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPermissionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::TVPApiModule.Properties.Settings.Default.TVPApiModule_yes_tvinci_ITProxy_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddDeviceCompletedEventHandler AddDeviceCompleted;
        
        /// <remarks/>
        public event GetEntitlementsCompletedEventHandler GetEntitlementsCompleted;
        
        /// <remarks/>
        public event GetCustomDataCompletedEventHandler GetCustomDataCompleted;
        
        /// <remarks/>
        public event GetUserPermissionCompletedEventHandler GetUserPermissionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddDevice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddDevice(string sAccNum, string sDeviceName, string sDNA, string sDeviceType, string sUsername) {
            this.Invoke("AddDevice", new object[] {
                        sAccNum,
                        sDeviceName,
                        sDNA,
                        sDeviceType,
                        sUsername});
        }
        
        /// <remarks/>
        public void AddDeviceAsync(string sAccNum, string sDeviceName, string sDNA, string sDeviceType, string sUsername) {
            this.AddDeviceAsync(sAccNum, sDeviceName, sDNA, sDeviceType, sUsername, null);
        }
        
        /// <remarks/>
        public void AddDeviceAsync(string sAccNum, string sDeviceName, string sDNA, string sDeviceType, string sUsername, object userState) {
            if ((this.AddDeviceOperationCompleted == null)) {
                this.AddDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDeviceOperationCompleted);
            }
            this.InvokeAsync("AddDevice", new object[] {
                        sAccNum,
                        sDeviceName,
                        sDNA,
                        sDeviceType,
                        sUsername}, this.AddDeviceOperationCompleted, userState);
        }
        
        private void OnAddDeviceOperationCompleted(object arg) {
            if ((this.AddDeviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddDeviceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEntitlements", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Entitlement[] GetEntitlements(string sAccountUUID, int[] iProductPK) {
            object[] results = this.Invoke("GetEntitlements", new object[] {
                        sAccountUUID,
                        iProductPK});
            return ((Entitlement[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEntitlementsAsync(string sAccountUUID, int[] iProductPK) {
            this.GetEntitlementsAsync(sAccountUUID, iProductPK, null);
        }
        
        /// <remarks/>
        public void GetEntitlementsAsync(string sAccountUUID, int[] iProductPK, object userState) {
            if ((this.GetEntitlementsOperationCompleted == null)) {
                this.GetEntitlementsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEntitlementsOperationCompleted);
            }
            this.InvokeAsync("GetEntitlements", new object[] {
                        sAccountUUID,
                        iProductPK}, this.GetEntitlementsOperationCompleted, userState);
        }
        
        private void OnGetEntitlementsOperationCompleted(object arg) {
            if ((this.GetEntitlementsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEntitlementsCompleted(this, new GetEntitlementsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCustomData(string sUDID, string sBundleID, string sCompontentID, string sEntitlementID) {
            object[] results = this.Invoke("GetCustomData", new object[] {
                        sUDID,
                        sBundleID,
                        sCompontentID,
                        sEntitlementID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomDataAsync(string sUDID, string sBundleID, string sCompontentID, string sEntitlementID) {
            this.GetCustomDataAsync(sUDID, sBundleID, sCompontentID, sEntitlementID, null);
        }
        
        /// <remarks/>
        public void GetCustomDataAsync(string sUDID, string sBundleID, string sCompontentID, string sEntitlementID, object userState) {
            if ((this.GetCustomDataOperationCompleted == null)) {
                this.GetCustomDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomDataOperationCompleted);
            }
            this.InvokeAsync("GetCustomData", new object[] {
                        sUDID,
                        sBundleID,
                        sCompontentID,
                        sEntitlementID}, this.GetCustomDataOperationCompleted, userState);
        }
        
        private void OnGetCustomDataOperationCompleted(object arg) {
            if ((this.GetCustomDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomDataCompleted(this, new GetCustomDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserPermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserPermission(string sUserName, string sUserType) {
            object[] results = this.Invoke("GetUserPermission", new object[] {
                        sUserName,
                        sUserType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPermissionAsync(string sUserName, string sUserType) {
            this.GetUserPermissionAsync(sUserName, sUserType, null);
        }
        
        /// <remarks/>
        public void GetUserPermissionAsync(string sUserName, string sUserType, object userState) {
            if ((this.GetUserPermissionOperationCompleted == null)) {
                this.GetUserPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPermissionOperationCompleted);
            }
            this.InvokeAsync("GetUserPermission", new object[] {
                        sUserName,
                        sUserType}, this.GetUserPermissionOperationCompleted, userState);
        }
        
        private void OnGetUserPermissionOperationCompleted(object arg) {
            if ((this.GetUserPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPermissionCompleted(this, new GetUserPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class Entitlement {
        
        private Account accountField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private string entitlementDataField;
        
        private EntitlementMetadata[] entitlementMetadatasField;
        
        private int entitlementPkField;
        
        private bool entitlementPkFieldSpecified;
        
        private string externalIdField;
        
        private System.DateTime lastModifiedDateField;
        
        private bool lastModifiedDateFieldSpecified;
        
        private string productIdField;
        
        private EntitlementStatus statusField;
        
        private System.DateTime statusDateField;
        
        private bool statusDateFieldSpecified;
        
        private string uuidField;
        
        /// <remarks/>
        public Account account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string entitlementData {
            get {
                return this.entitlementDataField;
            }
            set {
                this.entitlementDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entitlementMetadatas")]
        public EntitlementMetadata[] entitlementMetadatas {
            get {
                return this.entitlementMetadatasField;
            }
            set {
                this.entitlementMetadatasField = value;
            }
        }
        
        /// <remarks/>
        public int entitlementPk {
            get {
                return this.entitlementPkField;
            }
            set {
                this.entitlementPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entitlementPkSpecified {
            get {
                return this.entitlementPkFieldSpecified;
            }
            set {
                this.entitlementPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedDateSpecified {
            get {
                return this.lastModifiedDateFieldSpecified;
            }
            set {
                this.lastModifiedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public EntitlementStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime statusDate {
            get {
                return this.statusDateField;
            }
            set {
                this.statusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusDateSpecified {
            get {
                return this.statusDateFieldSpecified;
            }
            set {
                this.statusDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class Account {
        
        private AccountMetadata[] accountMetadatasField;
        
        private int accountPkField;
        
        private bool accountPkFieldSpecified;
        
        private string affiliateIdField;
        
        private string altcodeField;
        
        private Login defaultLoginField;
        
        private Device[] devicesField;
        
        private string emailField;
        
        private string externalIdField;
        
        private string firstNameField;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private System.DateTime lastModifiedDateField;
        
        private bool lastModifiedDateFieldSpecified;
        
        private string lastNameField;
        
        private Login[] loginsField;
        
        private string typeField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accountMetadatas")]
        public AccountMetadata[] accountMetadatas {
            get {
                return this.accountMetadatasField;
            }
            set {
                this.accountMetadatasField = value;
            }
        }
        
        /// <remarks/>
        public int accountPk {
            get {
                return this.accountPkField;
            }
            set {
                this.accountPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountPkSpecified {
            get {
                return this.accountPkFieldSpecified;
            }
            set {
                this.accountPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string affiliateId {
            get {
                return this.affiliateIdField;
            }
            set {
                this.affiliateIdField = value;
            }
        }
        
        /// <remarks/>
        public string altcode {
            get {
                return this.altcodeField;
            }
            set {
                this.altcodeField = value;
            }
        }
        
        /// <remarks/>
        public Login defaultLogin {
            get {
                return this.defaultLoginField;
            }
            set {
                this.defaultLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devices")]
        public Device[] devices {
            get {
                return this.devicesField;
            }
            set {
                this.devicesField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedDateSpecified {
            get {
                return this.lastModifiedDateFieldSpecified;
            }
            set {
                this.lastModifiedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("logins")]
        public Login[] logins {
            get {
                return this.loginsField;
            }
            set {
                this.loginsField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class AccountMetadata {
        
        private int accountMetadataPkField;
        
        private bool accountMetadataPkFieldSpecified;
        
        private byte[] binaryDataField;
        
        private string binaryDataMimeTypeField;
        
        private System.DateTime createdDateField;
        
        private bool createdDateFieldSpecified;
        
        private string dataField;
        
        private System.DateTime lastModifiedDateField;
        
        private bool lastModifiedDateFieldSpecified;
        
        private string nameField;
        
        private string uuidField;
        
        /// <remarks/>
        public int accountMetadataPk {
            get {
                return this.accountMetadataPkField;
            }
            set {
                this.accountMetadataPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountMetadataPkSpecified {
            get {
                return this.accountMetadataPkFieldSpecified;
            }
            set {
                this.accountMetadataPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string binaryDataMimeType {
            get {
                return this.binaryDataMimeTypeField;
            }
            set {
                this.binaryDataMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdDateSpecified {
            get {
                return this.createdDateFieldSpecified;
            }
            set {
                this.createdDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedDateSpecified {
            get {
                return this.lastModifiedDateFieldSpecified;
            }
            set {
                this.lastModifiedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class EntitlementMetadata {
        
        private string dataField;
        
        private int entitlementMetadataPkField;
        
        private bool entitlementMetadataPkFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int entitlementMetadataPk {
            get {
                return this.entitlementMetadataPkField;
            }
            set {
                this.entitlementMetadataPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entitlementMetadataPkSpecified {
            get {
                return this.entitlementMetadataPkFieldSpecified;
            }
            set {
                this.entitlementMetadataPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class DeviceType {
        
        private int deviceTypePkField;
        
        private bool deviceTypePkFieldSpecified;
        
        private DeviceTypeNames nameField;
        
        /// <remarks/>
        public int deviceTypePk {
            get {
                return this.deviceTypePkField;
            }
            set {
                this.deviceTypePkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceTypePkSpecified {
            get {
                return this.deviceTypePkFieldSpecified;
            }
            set {
                this.deviceTypePkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DeviceTypeNames name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public enum DeviceTypeNames {
        
        /// <remarks/>
        PC,
        
        /// <remarks/>
        Device,
        
        /// <remarks/>
        Silverlight,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class DeviceMetadata {
        
        private string dataField;
        
        private int deviceMetadataPkField;
        
        private bool deviceMetadataPkFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public int deviceMetadataPk {
            get {
                return this.deviceMetadataPkField;
            }
            set {
                this.deviceMetadataPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceMetadataPkSpecified {
            get {
                return this.deviceMetadataPkFieldSpecified;
            }
            set {
                this.deviceMetadataPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class Device {
        
        private string accountUuidField;
        
        private string altcodeField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private DeviceMetadata[] deviceMetadatasField;
        
        private int devicePkField;
        
        private bool devicePkFieldSpecified;
        
        private DeviceType deviceTypeField;
        
        private string drmImplField;
        
        private string externalIdField;
        
        private string hardwareIdField;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private string nameField;
        
        private string uuidField;
        
        /// <remarks/>
        public string accountUuid {
            get {
                return this.accountUuidField;
            }
            set {
                this.accountUuidField = value;
            }
        }
        
        /// <remarks/>
        public string altcode {
            get {
                return this.altcodeField;
            }
            set {
                this.altcodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deviceMetadatas")]
        public DeviceMetadata[] deviceMetadatas {
            get {
                return this.deviceMetadatasField;
            }
            set {
                this.deviceMetadatasField = value;
            }
        }
        
        /// <remarks/>
        public int devicePk {
            get {
                return this.devicePkField;
            }
            set {
                this.devicePkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool devicePkSpecified {
            get {
                return this.devicePkFieldSpecified;
            }
            set {
                this.devicePkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DeviceType deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string drmImpl {
            get {
                return this.drmImplField;
            }
            set {
                this.drmImplField = value;
            }
        }
        
        /// <remarks/>
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public string hardwareId {
            get {
                return this.hardwareIdField;
            }
            set {
                this.hardwareIdField = value;
            }
        }
        
        /// <remarks/>
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class LoginRole {
        
        private string descriptionField;
        
        private int loginRolePkField;
        
        private bool loginRolePkFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int loginRolePk {
            get {
                return this.loginRolePkField;
            }
            set {
                this.loginRolePkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginRolePkSpecified {
            get {
                return this.loginRolePkFieldSpecified;
            }
            set {
                this.loginRolePkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class LoginMetadata {
        
        private byte[] binaryDataField;
        
        private string binaryDataMimeTypeField;
        
        private System.DateTime createdDateField;
        
        private bool createdDateFieldSpecified;
        
        private string dataField;
        
        private System.DateTime lastModifiedDateField;
        
        private bool lastModifiedDateFieldSpecified;
        
        private int logingMetadataPkField;
        
        private bool logingMetadataPkFieldSpecified;
        
        private string nameField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string binaryDataMimeType {
            get {
                return this.binaryDataMimeTypeField;
            }
            set {
                this.binaryDataMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdDateSpecified {
            get {
                return this.createdDateFieldSpecified;
            }
            set {
                this.createdDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedDateSpecified {
            get {
                return this.lastModifiedDateFieldSpecified;
            }
            set {
                this.lastModifiedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int logingMetadataPk {
            get {
                return this.logingMetadataPkField;
            }
            set {
                this.logingMetadataPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool logingMetadataPkSpecified {
            get {
                return this.logingMetadataPkFieldSpecified;
            }
            set {
                this.logingMetadataPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class EntitlementFilter {
        
        private int entitlementFilterPkField;
        
        private bool entitlementFilterPkFieldSpecified;
        
        private string filterDataField;
        
        private string filterTypeField;
        
        private int loginPkField;
        
        private bool loginPkFieldSpecified;
        
        /// <remarks/>
        public int entitlementFilterPk {
            get {
                return this.entitlementFilterPkField;
            }
            set {
                this.entitlementFilterPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entitlementFilterPkSpecified {
            get {
                return this.entitlementFilterPkFieldSpecified;
            }
            set {
                this.entitlementFilterPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string filterData {
            get {
                return this.filterDataField;
            }
            set {
                this.filterDataField = value;
            }
        }
        
        /// <remarks/>
        public string filterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
            }
        }
        
        /// <remarks/>
        public int loginPk {
            get {
                return this.loginPkField;
            }
            set {
                this.loginPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginPkSpecified {
            get {
                return this.loginPkFieldSpecified;
            }
            set {
                this.loginPkFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public partial class Login {
        
        private string accountUuidField;
        
        private string altcodeField;
        
        private string emailField;
        
        private EntitlementFilter[] entitlementFiltersField;
        
        private string externalIdField;
        
        private string firstNameField;
        
        private bool isActiveField;
        
        private string lastNameField;
        
        private LoginMetadata[] loginMetadatasField;
        
        private int loginPkField;
        
        private bool loginPkFieldSpecified;
        
        private LoginRole loginRoleField;
        
        private string usernameField;
        
        private string uuidField;
        
        /// <remarks/>
        public string accountUuid {
            get {
                return this.accountUuidField;
            }
            set {
                this.accountUuidField = value;
            }
        }
        
        /// <remarks/>
        public string altcode {
            get {
                return this.altcodeField;
            }
            set {
                this.altcodeField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entitlementFilters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public EntitlementFilter[] entitlementFilters {
            get {
                return this.entitlementFiltersField;
            }
            set {
                this.entitlementFiltersField = value;
            }
        }
        
        /// <remarks/>
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("loginMetadatas")]
        public LoginMetadata[] loginMetadatas {
            get {
                return this.loginMetadatasField;
            }
            set {
                this.loginMetadatasField = value;
            }
        }
        
        /// <remarks/>
        public int loginPk {
            get {
                return this.loginPkField;
            }
            set {
                this.loginPkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginPkSpecified {
            get {
                return this.loginPkFieldSpecified;
            }
            set {
                this.loginPkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public LoginRole loginRole {
            get {
                return this.loginRoleField;
            }
            set {
                this.loginRoleField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://opencase.extend.com/em")]
    public enum EntitlementStatus {
        
        /// <remarks/>
        NEW,
        
        /// <remarks/>
        REVOKED,
        
        /// <remarks/>
        REISSUED,
        
        /// <remarks/>
        COMPLETE,
        
        /// <remarks/>
        DELETED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddDeviceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetEntitlementsCompletedEventHandler(object sender, GetEntitlementsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEntitlementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEntitlementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Entitlement[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Entitlement[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCustomDataCompletedEventHandler(object sender, GetCustomDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetUserPermissionCompletedEventHandler(object sender, GetUserPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591