// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using System;

namespace WebAPI.Models.ConditionalAccess
{
    [Serializable]
    public enum KalturaDrmSchemeName
    {
        PLAYREADY_CENC = 0,
        WIDEVINE_CENC = 1,
        FAIRPLAY = 2,
        WIDEVINE = 3,
        PLAYREADY = 4,
        CUSTOM_DRM = 5
    }
}
