// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using System;
using System.Xml.Serialization;
using WebAPI.Models.General;

namespace WebAPI.Models.ConditionalAccess
{
    [XmlInclude(typeof(KalturaBumpersPlaybackPluginData))]
    [Serializable]
    public partial class KalturaPlaybackPluginData : KalturaOTTObject
    {
    }
}
