// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;
using WebAPI.Models.General;

namespace WebAPI.Models.ConditionalAccess
{
    [Serializable]
    public partial class KalturaPlaybackContextOptions : KalturaOTTObject
    {
        /// <summary>
        /// Protocol of the specific media object (http / https).
        /// </summary>
        [DataMember(Name = "mediaProtocol")]
        [JsonProperty("mediaProtocol")]
        [XmlElement("mediaProtocol")]
        public string MediaProtocol { get; set; }

        /// <summary>
        /// Playback streamer type: applehttp, mpegdash, url, smothstreaming, multicast, none
        /// </summary>
        [DataMember(Name = "streamerType")]
        [JsonProperty("streamerType")]
        [XmlElement("streamerType")]
        public string StreamerType { get; set; }

        /// <summary>
        /// List of comma separated media file IDs
        /// </summary>
        [DataMember(Name = "assetFileIds")]
        [JsonProperty("assetFileIds")]
        [XmlElement("assetFileIds")]
        [SchemeProperty(DynamicMinInt = 1)]
        public string AssetFileIds { get; set; }

        /// <summary>
        /// key/value map field for extra data
        /// </summary>
        [DataMember(Name = "adapterData")]
        [JsonProperty("adapterData")]
        [XmlElement("adapterData")]
        public SerializableDictionary<string, KalturaStringValue> AdapterData { get; set; }

        /// <summary>
        /// Playback context type
        /// </summary>
        [DataMember(Name = "context")]
        [JsonProperty("context")]
        [XmlElement("context", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public KalturaPlaybackContextType? Context { get; set; }

        /// <summary>
        /// Url type
        /// </summary>
        [DataMember(Name = "urlType")]
        [JsonProperty("urlType")]
        [XmlElement("urlType")]
        public KalturaUrlType UrlType { get; set; }
    }
}
