// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace WebAPI.Models.ConditionalAccess
{
    [Serializable]
    public partial class KalturaCustomDrmPlaybackPluginData : KalturaDrmPlaybackPluginData
    {
        /// <summary>
        /// Custom DRM license data
        /// </summary>
        [DataMember(Name = "data")]
        [JsonProperty("data")]
        [XmlElement("data")]
        public string Data { get; set; }
    }
}
