// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using System;

namespace WebAPI.Models.ConditionalAccess
{
    [Serializable]
    public enum KalturaTransactionType
    {
        ppv = 0,
        subscription = 1,
        collection = 2,
        programAssetGroupOffer = 3
    }
}
