// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Models.General;

namespace WebAPI.Models.ConditionalAccess
{
    [Serializable]
    public partial class KalturaPlaybackContext : KalturaOTTObject
    {
        /// <summary>
        /// Sources
        /// </summary>
        [DataMember(Name = "sources")]
        [JsonProperty("sources")]
        [XmlArray("sources", IsNullable = true)]
        [XmlArrayItem("item")]
        public List<KalturaPlaybackSource> Sources { get; set; }

        /// <summary>
        /// Actions
        /// </summary>
        [DataMember(Name = "actions")]
        [JsonProperty("actions")]
        [XmlArray("actions", IsNullable = true)]
        [XmlArrayItem("item")]
        public List<KalturaRuleAction> Actions { get; set; }

        /// <summary>
        /// Messages
        /// </summary>
        [DataMember(Name = "messages")]
        [JsonProperty("messages")]
        [XmlArray("messages", IsNullable = true)]
        [XmlArrayItem("item")]
        public List<KalturaAccessControlMessage> Messages { get; set; }

        /// <summary>
        /// Playback captions
        /// </summary>
        [DataMember(Name = "playbackCaptions")]
        [JsonProperty("playbackCaptions")]
        [XmlArray("playbackCaptions", IsNullable = true)]
        [XmlArrayItem("item")]
        public List<KalturaCaptionPlaybackPluginData> PlaybackCaptions { get; set; }

        /// <summary>
        /// Plugins
        /// </summary>
        [DataMember(Name = "plugins")]
        [JsonProperty("plugins")]
        [XmlArray("plugins", IsNullable = true)]
        [XmlArrayItem("item")]
        public List<KalturaPlaybackPluginData> Plugins { get; set; }
    }
}
