// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using System;

namespace WebAPI.Models.ConditionalAccess
{
    [Serializable]
    public enum KalturaRuleActionType
    {
        BLOCK = 0,
        START_DATE_OFFSET = 1,
        END_DATE_OFFSET = 2,
        USER_BLOCK = 3,
        ALLOW_PLAYBACK = 4,
        BLOCK_PLAYBACK = 5,
        APPLY_DISCOUNT_MODULE = 6,
        APPLY_PLAYBACK_ADAPTER = 7,
        FILTER = 8,
        ASSET_LIFE_CYCLE_TRANSITION = 9,
        APPLY_FREE_PLAYBACK = 10,
        FilterAssetByKsql = 11,
        FilterFileByQualityInDiscovery = 12,
        FilterFileByQualityInPlayback = 13,
        FilterFileByFileTypeIdForAssetTypeInDiscovery = 14,
        FilterFileByFileTypeIdForAssetTypeInPlayback = 15,
        FilterFileByFileTypeIdInDiscovery = 16,
        FilterFileByFileTypeIdInPlayback = 17,
        FilterFileByAudioCodecInDiscovery = 18,
        FilterFileByAudioCodecInPlayback = 19,
        FilterFileByVideoCodecInDiscovery = 20,
        FilterFileByVideoCodecInPlayback = 21,
        FilterFileByStreamerTypeInDiscovery = 22,
        FilterFileByStreamerTypeInPlayback = 23,
        FilterFileByLabelInDiscovery = 24,
        FilterFileByLabelInPlayback = 25,
        FilterFileByDynamicDataInDiscovery = 26,
        FilterFileByDynamicDataInPlayback = 27
    }
}
