// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;

namespace WebAPI.Models.General
{
    [Serializable]
    public abstract partial class KalturaPersistedFilter<KalturaT> : KalturaFilter<KalturaT>, IKalturaPersistedFilter
        where KalturaT : struct, IFormattable, IConvertible, IComparable
    {
        /// <summary>
        /// Name for the presisted filter. If empty, no action will be done. If has value, the filter will be saved and persisted in user's search history.
        /// </summary>
        [DataMember(Name = "name")]
        [JsonProperty("name")]
        [XmlElement("name", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [ValidationException(SchemeValidationType.FILTER_SUFFIX)]
        public string Name { get; set; }
    }
}
