// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;

namespace WebAPI.Models.General
{
    /// <summary>
    /// Message
    /// </summary>
    [Serializable]
    public partial class KalturaMessage : KalturaOTTObject
    {
        /// <summary>
        /// Massage code
        /// </summary>
        [DataMember(Name = "code")]
        [JsonProperty("code")]
        [XmlElement("code")]
        public int Code { get; set; }

        /// <summary>
        /// Message details
        /// </summary>
        [DataMember(Name = "message")]
        [JsonProperty("message")]
        [XmlElement("message")]
        public string Message { get; set; }

        /// <summary>
        /// Message args
        /// </summary>
        [DataMember(Name = "args")]
        [JsonProperty("args")]
        [XmlElement("args", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public SerializableDictionary<string, KalturaStringValue> Args { get; set; }
    }
}
