@startuml
allowmixing

object Ingest
object EPGInvalidator
object EPGService
object EPGNotification
object AmazonIoT
object FutureIoT
queue Queue1
queue Queue2
database EPGCache


Ingest -> Queue1 : 1 {liveAssetId,startDate,endDate,\ndisableNotification(from Ingest-request)}
Queue1 -> EPGInvalidator: 2
EPGInvalidator --> EPGService : 3 liveAssetId
EPGService --> EPGCache : 4 liveAssetId
EPGInvalidator -> Queue2 : 5 {liveAssetId,startDate,\nendDate,disableNotification}
Queue2 -> EPGNotification : 6
EPGNotification -> EPGNotification : rules if we should send
EPGNotification --> AmazonIoT : 7
EPGNotification --> FutureIoT : 7
@enduml