// code generated by github.com/kaltura/ott-tool-codegen-csharp/OTT.Tool.Codegen. DO NOT EDIT.
using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using WebAPI.Managers.Scheme;
using WebAPI.Models.General;

namespace WebAPI.Models.API
{
    [Serializable]
    public partial class KalturaTimeShiftedTvPartnerSettings : KalturaOTTObject
    {
        /// <summary>
        /// Is catch-up enabled
        /// </summary>
        [DataMember(Name = "catchUpEnabled")]
        [JsonProperty("catchUpEnabled")]
        [XmlElement("catchUpEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("catch_up_enabled")]
        public bool? CatchUpEnabled { get; set; }

        /// <summary>
        /// Is c-dvr enabled
        /// </summary>
        [DataMember(Name = "cdvrEnabled")]
        [JsonProperty("cdvrEnabled")]
        [XmlElement("cdvrEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("cdvr_enabled")]
        public bool? CdvrEnabled { get; set; }

        /// <summary>
        /// Is start-over enabled
        /// </summary>
        [DataMember(Name = "startOverEnabled")]
        [JsonProperty("startOverEnabled")]
        [XmlElement("startOverEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("start_over_enabled")]
        public bool? StartOverEnabled { get; set; }

        /// <summary>
        /// Is trick-play enabled
        /// </summary>
        [DataMember(Name = "trickPlayEnabled")]
        [JsonProperty("trickPlayEnabled")]
        [XmlElement("trickPlayEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("trick_play_enabled")]
        public bool? TrickPlayEnabled { get; set; }

        /// <summary>
        /// Is recording schedule window enabled
        /// </summary>
        [DataMember(Name = "recordingScheduleWindowEnabled")]
        [JsonProperty("recordingScheduleWindowEnabled")]
        [XmlElement("recordingScheduleWindowEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("recording_schedule_window_enabled")]
        public bool? RecordingScheduleWindowEnabled { get; set; }

        /// <summary>
        /// Is recording protection enabled
        /// </summary>
        [DataMember(Name = "protectionEnabled")]
        [JsonProperty("protectionEnabled")]
        [XmlElement("protectionEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public bool? ProtectionEnabled { get; set; }

        /// <summary>
        /// Catch-up buffer length
        /// </summary>
        [DataMember(Name = "catchUpBufferLength")]
        [JsonProperty("catchUpBufferLength")]
        [XmlElement("catchUpBufferLength", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("catch_up_buffer_length")]
        public long? CatchUpBufferLength { get; set; }

        /// <summary>
        /// Trick play buffer length
        /// </summary>
        [DataMember(Name = "trickPlayBufferLength")]
        [JsonProperty("trickPlayBufferLength")]
        [XmlElement("trickPlayBufferLength", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("trick_play_buffer_length")]
        public long? TrickPlayBufferLength { get; set; }

        /// <summary>
        /// Recording schedule window. Indicates how long (in minutes) after the program starts it is allowed to schedule the recording
        /// </summary>
        [DataMember(Name = "recordingScheduleWindow")]
        [JsonProperty("recordingScheduleWindow")]
        [XmlElement("recordingScheduleWindow", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        [OldStandardProperty("recording_schedule_window")]
        public long? RecordingScheduleWindow { get; set; }

        /// <summary>
        /// Indicates how long (in seconds) before the program starts the recording will begin
        /// </summary>
        [DataMember(Name = "paddingBeforeProgramStarts")]
        [JsonProperty("paddingBeforeProgramStarts")]
        [XmlElement("paddingBeforeProgramStarts", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinLong = 0)]
        public long? PaddingBeforeProgramStarts { get; set; }

        /// <summary>
        /// Indicates how long (in seconds) after the program ends the recording will end
        /// </summary>
        [DataMember(Name = "paddingAfterProgramEnds")]
        [JsonProperty("paddingAfterProgramEnds")]
        [XmlElement("paddingAfterProgramEnds", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinLong = 0)]
        public long? PaddingAfterProgramEnds { get; set; }

        /// <summary>
        /// Specify the time in days that a recording should be protected. Start time begins at protection request.
        /// </summary>
        [DataMember(Name = "protectionPeriod")]
        [JsonProperty("protectionPeriod")]
        [XmlElement("protectionPeriod", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 0)]
        public int? ProtectionPeriod { get; set; }

        /// <summary>
        /// Indicates how many percent of the quota can be used for protection
        /// </summary>
        [DataMember(Name = "protectionQuotaPercentage")]
        [JsonProperty("protectionQuotaPercentage")]
        [XmlElement("protectionQuotaPercentage", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 10, MaxInteger = 100)]
        public int? ProtectionQuotaPercentage { get; set; }

        /// <summary>
        /// Specify the time in days that a recording should be kept for user. Start time begins with the program end date.
        /// </summary>
        [DataMember(Name = "recordingLifetimePeriod")]
        [JsonProperty("recordingLifetimePeriod")]
        [XmlElement("recordingLifetimePeriod", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 0)]
        public int? RecordingLifetimePeriod { get; set; }

        /// <summary>
        /// The time in days before the recording lifetime is due from which the client should be able to warn user about deletion.
        /// </summary>
        [DataMember(Name = "cleanupNoticePeriod")]
        [JsonProperty("cleanupNoticePeriod")]
        [XmlElement("cleanupNoticePeriod", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 0)]
        public int? CleanupNoticePeriod { get; set; }

        /// <summary>
        /// Is recording of series enabled
        /// </summary>
        [DataMember(Name = "seriesRecordingEnabled")]
        [JsonProperty("seriesRecordingEnabled")]
        [XmlElement("seriesRecordingEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public bool? SeriesRecordingEnabled { get; set; }

        /// <summary>
        /// Is recording playback for non-entitled channel enables
        /// </summary>
        [DataMember(Name = "nonEntitledChannelPlaybackEnabled")]
        [JsonProperty("nonEntitledChannelPlaybackEnabled")]
        [XmlElement("nonEntitledChannelPlaybackEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public bool? NonEntitledChannelPlaybackEnabled { get; set; }

        /// <summary>
        /// Is recording playback for non-existing channel enables
        /// </summary>
        [DataMember(Name = "nonExistingChannelPlaybackEnabled")]
        [JsonProperty("nonExistingChannelPlaybackEnabled")]
        [XmlElement("nonExistingChannelPlaybackEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public bool? NonExistingChannelPlaybackEnabled { get; set; }

        /// <summary>
        /// Quota Policy
        /// </summary>
        [DataMember(Name = "quotaOveragePolicy")]
        [JsonProperty("quotaOveragePolicy", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("quotaOveragePolicy", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public KalturaQuotaOveragePolicy? QuotaOveragePolicy { get; set; }

        /// <summary>
        /// Protection Policy
        /// </summary>
        [DataMember(Name = "protectionPolicy")]
        [JsonProperty("protectionPolicy", NullValueHandling = NullValueHandling.Ignore)]
        [XmlElement("protectionPolicy", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public KalturaProtectionPolicy? ProtectionPolicy { get; set; }

        /// <summary>
        /// The time in days for recovery recording that was delete by Auto Delete .
        /// </summary>
        [DataMember(Name = "recoveryGracePeriod")]
        [JsonProperty("recoveryGracePeriod")]
        [XmlElement("recoveryGracePeriod", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 0)]
        public int? RecoveryGracePeriod { get; set; }

        /// <summary>
        /// Is private copy enabled for the account
        /// </summary>
        [DataMember(Name = "privateCopyEnabled")]
        [JsonProperty("privateCopyEnabled")]
        [XmlElement("privateCopyEnabled", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public bool? PrivateCopyEnabled { get; set; }

        /// <summary>
        /// Quota in seconds
        /// </summary>
        [DataMember(Name = "defaultQuota")]
        [JsonProperty("defaultQuota")]
        [XmlElement("defaultQuota", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = -1)]
        public int? DefaultQuota { get; set; }

        /// <summary>
        /// Define whatever the partner enables the Personal Padding and Immediate / Stop recording services to the partner. Default value should be FALSE
        /// </summary>
        [DataMember(Name = "personalizedRecording")]
        [JsonProperty("personalizedRecording")]
        [XmlElement("personalizedRecording", IsNullable = true)]
        [SchemeProperty(IsNullable = true)]
        public bool? PersonalizedRecording { get; set; }

        /// <summary>
        /// Define the max allowed number of parallel recordings. Default NULL unlimited
        /// </summary>
        [DataMember(Name = "maxRecordingConcurrency")]
        [JsonProperty("maxRecordingConcurrency")]
        [XmlElement("maxRecordingConcurrency", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 0, MaxInteger = 9999)]
        public int? MaxRecordingConcurrency { get; set; }

        /// <summary>
        /// Define the max grace margin time for overlapping recording. Default NULL 0 margin
        /// </summary>
        [DataMember(Name = "maxConcurrencyMargin")]
        [JsonProperty("maxConcurrencyMargin")]
        [XmlElement("maxConcurrencyMargin", IsNullable = true)]
        [SchemeProperty(IsNullable = true, MinInteger = 0, MaxInteger = 9999)]
        public int? MaxConcurrencyMargin { get; set; }
    }
}
