// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: channelslist.xsd
// Creation Date: 11/02/2013 15:26:20
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Tvinci.Data.TVMDataLoader.Protocols.ChannelsList
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}

	[Serializable]
	public enum file_quality
	{
		[XmlEnum(Name="low")] low,
		[XmlEnum(Name="medium")] medium,
		[XmlEnum(Name="high")] high
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class channelCollection : ArrayList
	{
		public channel Add(channel obj)
		{
			base.Add(obj);
			return obj;
		}

		public channel Add()
		{
			return Add(new channel());
		}

		public void Insert(int index, channel obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(channel obj)
		{
			base.Remove(obj);
		}

		new public channel this[int index]
		{
			get { return (channel) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlRoot(ElementName="ChannelsList",IsNullable=false),Serializable]
	public partial class ChannelsList
	{

		[XmlElement(Type=typeof(root),ElementName="root",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public root __root;
		
		[XmlIgnore]
		public root root
		{
			get
			{
				if (__root == null) __root = new root();		
				return __root;
			}
			set {__root = value;}
		}

		[XmlElement(Type=typeof(response),ElementName="response",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public response __response;
		
		[XmlIgnore]
		public response response
		{
			get
			{
				if (__response == null) __response = new response();		
				return __response;
			}
			set {__response = value;}
		}

		public ChannelsList()
		{
		}

		public void MakeSchemaCompliant()
		{
			root.MakeSchemaCompliant();
			response.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="root"),Serializable]
	public partial class root
	{

		[XmlElement(Type=typeof(request),ElementName="request",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public request __request;
		
		[XmlIgnore]
		public request request
		{
			get
			{
				if (__request == null) __request = new request();		
				return __request;
			}
			set {__request = value;}
		}

		[XmlElement(Type=typeof(flashvars),ElementName="flashvars",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public flashvars __flashvars;
		
		[XmlIgnore]
		public flashvars flashvars
		{
			get
			{
				if (__flashvars == null) __flashvars = new flashvars();		
				return __flashvars;
			}
			set {__flashvars = value;}
		}

		public root()
		{
		}

		public void MakeSchemaCompliant()
		{
			request.MakeSchemaCompliant();
			flashvars.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="request"),Serializable]
	public partial class request
	{

		[XmlAttribute(AttributeName="type",Form=XmlSchemaForm.Unqualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __type;
		
		[XmlIgnore]
		public string type
		{ 
			get { return __type; }
			set { __type = value; }
		}

		[XmlElement(Type=typeof(category),ElementName="category",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public category __category;
		
		[XmlIgnore]
		public category category
		{
			get
			{
				if (__category == null) __category = new category();		
				return __category;
			}
			set {__category = value;}
		}

		public request()
		{
			type = "channels_list";
		}

		public void MakeSchemaCompliant()
		{
			category.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="category"),Serializable]
	public partial class category
	{

		[XmlAttribute(AttributeName="id",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __id;
		
		[XmlIgnore]
		public string id
		{ 
			get { return __id; }
			set { __id = value; }
		}

		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Value;
		
		[XmlIgnore]
		public string Value
		{ 
			get { return __Value; }
			set { __Value = value; }
		}

		public category()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="flashvars"),Serializable]
	public partial class flashvars
	{

		[XmlAttribute(AttributeName="auto_play",Form=XmlSchemaForm.Unqualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __auto_play;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __auto_playSpecified;
		
		[XmlIgnore]
		public bool auto_play
		{ 
			get { return __auto_play; }
			set { __auto_play = value; __auto_playSpecified = true; }
		}

		[XmlAttribute(AttributeName="zip",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __zip;
		
		[XmlIgnore]
		public string zip
		{ 
			get { return __zip; }
			set { __zip = value; }
		}

		[XmlAttribute(AttributeName="file_format",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __file_format;
		
		[XmlIgnore]
		public string file_format
		{ 
			get { return __file_format; }
			set { __file_format = value; }
		}

		[XmlAttribute(AttributeName="file_quality",Form=XmlSchemaForm.Unqualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public file_quality __file_quality;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __file_qualitySpecified;
		
		[XmlIgnore]
		public file_quality file_quality
		{ 
			get { return __file_quality; }
			set { __file_quality = value; __file_qualitySpecified = true; }
		}

		[XmlAttribute(AttributeName="no_cache",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __no_cache;
		
		[XmlIgnore]
		public string no_cache
		{ 
			get { return __no_cache; }
			set { __no_cache = value; }
		}

		[XmlAttribute(AttributeName="pic_size1",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __pic_size1;
		
		[XmlIgnore]
		public string pic_size1
		{ 
			get { return __pic_size1; }
			set { __pic_size1 = value; }
		}

		[XmlAttribute(AttributeName="tvinci_guid",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __tvinci_guid;
		
		[XmlIgnore]
		public string tvinci_guid
		{ 
			get { return __tvinci_guid; }
			set { __tvinci_guid = value; }
		}

		[XmlAttribute(AttributeName="with_channels",Form=XmlSchemaForm.Unqualified,DataType="boolean")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __with_channels;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __with_channelsSpecified;
		
		[XmlIgnore]
		public bool with_channels
		{ 
			get { return __with_channels; }
			set { __with_channels = value; __with_channelsSpecified = true; }
		}

		[XmlAttribute(AttributeName="player_un",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __player_un;
		
		[XmlIgnore]
		public string player_un
		{ 
			get { return __player_un; }
			set { __player_un = value; }
		}

		[XmlAttribute(AttributeName="player_pass",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __player_pass;
		
		[XmlIgnore]
		public string player_pass
		{ 
			get { return __player_pass; }
			set { __player_pass = value; }
		}

		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Value;
		
		[XmlIgnore]
		public string Value
		{ 
			get { return __Value; }
			set { __Value = value; }
		}

		public flashvars()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="response"),Serializable]
	public partial class response
	{

		[XmlAttribute(AttributeName="type",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __type;
		
		[XmlIgnore]
		public string type
		{ 
			get { return __type; }
			set { __type = value; }
		}

		[XmlElement(Type=typeof(responsecategory),ElementName="category",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public responsecategory __category;
		
		[XmlIgnore]
		public responsecategory category
		{
			get
			{
				if (__category == null) __category = new responsecategory();		
				return __category;
			}
			set {__category = value;}
		}

		public response()
		{
		}

		public void MakeSchemaCompliant()
		{
			category.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="responsecategory"),Serializable]
	public partial class responsecategory
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return channelCollection.GetEnumerator();
		}

		public channel Add(channel obj)
		{
			return channelCollection.Add(obj);
		}

		[XmlIgnore]
		public channel this[int index]
		{
			get { return (channel) channelCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return channelCollection.Count; }
        }

        public void Clear()
		{
			channelCollection.Clear();
        }

		public channel Remove(int index) 
		{ 
            channel obj = channelCollection[index];
            channelCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            channelCollection.Remove(obj);
        }

		[XmlAttribute(AttributeName="id",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __id;
		
		[XmlIgnore]
		public string id
		{ 
			get { return __id; }
			set { __id = value; }
		}

		[XmlElement(Type=typeof(channel),ElementName="channel",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public channelCollection __channelCollection;
		
		[XmlIgnore]
		public channelCollection channelCollection
		{
			get
			{
				if (__channelCollection == null) __channelCollection = new channelCollection();
				return __channelCollection;
			}
			set {__channelCollection = value;}
		}

		public responsecategory()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="channel"),Serializable]
	public partial class channel
	{

		[XmlAttribute(AttributeName="id",Form=XmlSchemaForm.Unqualified,DataType="int")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __id;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __idSpecified;
		
		[XmlIgnore]
		public int id
		{ 
			get { return __id; }
			set { __id = value; __idSpecified = true; }
		}

		[XmlAttribute(AttributeName="pic_size1",Form=XmlSchemaForm.Unqualified,DataType="anyURI")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __pic_size1;
		
		[XmlIgnore]
		public string pic_size1
		{ 
			get { return __pic_size1; }
			set { __pic_size1 = value; }
		}

		[XmlAttribute(AttributeName="title",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __title;
		
		[XmlIgnore]
		public string title
		{ 
			get { return __title; }
			set { __title = value; }
		}

		[XmlAttribute(AttributeName="media_count",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __media_count;
		
		[XmlIgnore]
		public string media_count
		{ 
			get { return __media_count; }
			set { __media_count = value; }
		}

		[XmlAttribute(AttributeName="description",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __description;
		
		[XmlIgnore]
		public string description
		{ 
			get { return __description; }
			set { __description = value; }
		}

		[XmlAttribute(AttributeName="linear_start_time",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __linear_start_time;
		
		[XmlIgnore]
		public string linear_start_time
		{ 
			get { return __linear_start_time; }
			set { __linear_start_time = value; }
		}

		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Value;
		
		[XmlIgnore]
		public string Value
		{ 
			get { return __Value; }
			set { __Value = value; }
		}

		public channel()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}
}
