// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: GetAccountInfo.xsd
// Creation Date: 11/7/2011 2:45:52 PM
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace XmlModels.GetAccountInfo
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class informationCollection : ArrayList
	{
		public information Add(information obj)
		{
			base.Add(obj);
			return obj;
		}

		public information Add()
		{
			return Add(new information());
		}

		public void Insert(int index, information obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(information obj)
		{
			base.Remove(obj);
		}

		new public information this[int index]
		{
			get { return (information) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class accountCollection : ArrayList
	{
		public account Add(account obj)
		{
			base.Add(obj);
			return obj;
		}

		public account Add()
		{
			return Add(new account());
		}

		public void Insert(int index, account obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(account obj)
		{
			base.Remove(obj);
		}

		new public account this[int index]
		{
			get { return (account) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class streamsCollection : ArrayList
	{
		public streams Add(streams obj)
		{
			base.Add(obj);
			return obj;
		}

		public streams Add()
		{
			return Add(new streams());
		}

		public void Insert(int index, streams obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(streams obj)
		{
			base.Remove(obj);
		}

		new public streams this[int index]
		{
			get { return (streams) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public partial class streamCollection : ArrayList
	{
		public stream Add(stream obj)
		{
			base.Add(obj);
			return obj;
		}

		public stream Add()
		{
			return Add(new stream());
		}

		public void Insert(int index, stream obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(stream obj)
		{
			base.Remove(obj);
		}

		new public stream this[int index]
		{
			get { return (stream) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlRoot(ElementName="GetAccountInfo",IsNullable=false),Serializable]
	public partial class GetAccountInfo
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return accountCollection.GetEnumerator();
		}

		public account Add(account obj)
		{
			return accountCollection.Add(obj);
		}

		[XmlIgnore]
		public account this[int index]
		{
			get { return (account) accountCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return accountCollection.Count; }
        }

        public void Clear()
		{
			accountCollection.Clear();
        }

		public account Remove(int index) 
		{ 
            account obj = accountCollection[index];
            accountCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            accountCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(account),ElementName="account",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public accountCollection __accountCollection;
		
		[XmlIgnore]
		public accountCollection accountCollection
		{
			get
			{
				if (__accountCollection == null) __accountCollection = new accountCollection();
				return __accountCollection;
			}
			set {__accountCollection = value;}
		}

		public GetAccountInfo()
		{
		}

		public void MakeSchemaCompliant()
		{
			if (accountCollection.Count == 0)
			{
				account _c = accountCollection.Add();
				_c.MakeSchemaCompliant();
			}
			else foreach (account _c in accountCollection) _c.MakeSchemaCompliant();
		}
	}


	[XmlType(TypeName="account"),Serializable]
	public partial class account
	{

		[XmlElement(Type=typeof(information),ElementName="information",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public informationCollection __informationCollection;
		
		[XmlIgnore]
		public informationCollection informationCollection
		{
			get
			{
				if (__informationCollection == null) __informationCollection = new informationCollection();
				return __informationCollection;
			}
			set {__informationCollection = value;}
		}

		[XmlElement(Type=typeof(streams),ElementName="streams",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public streamsCollection __streamsCollection;
		
		[XmlIgnore]
		public streamsCollection streamsCollection
		{
			get
			{
				if (__streamsCollection == null) __streamsCollection = new streamsCollection();
				return __streamsCollection;
			}
			set {__streamsCollection = value;}
		}

		public account()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="information"),Serializable]
	public partial class information
	{

		[XmlElement(ElementName="distributor",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __distributor;
		
		[XmlIgnore]
		public string distributor
		{ 
			get { return __distributor; }
			set { __distributor = value; }
		}

		[XmlElement(ElementName="contract",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __contract;
		
		[XmlIgnore]
		public string contract
		{ 
			get { return __contract; }
			set { __contract = value; }
		}

		[XmlElement(ElementName="date",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __date;
		
		[XmlIgnore]
		public string date
		{ 
			get { return __date; }
			set { __date = value; }
		}

		[XmlElement(ElementName="pay",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __pay;
		
		[XmlIgnore]
		public string pay
		{ 
			get { return __pay; }
			set { __pay = value; }
		}

		[XmlElement(ElementName="email",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __email;
		
		[XmlIgnore]
		public string email
		{ 
			get { return __email; }
			set { __email = value; }
		}

		[XmlElement(ElementName="logo",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __logo;
		
		[XmlIgnore]
		public string logo
		{ 
			get { return __logo; }
			set { __logo = value; }
		}

		public information()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="streams"),Serializable]
	public partial class streams
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return streamCollection.GetEnumerator();
		}

		public stream Add(stream obj)
		{
			return streamCollection.Add(obj);
		}

		[XmlIgnore]
		public stream this[int index]
		{
			get { return (stream) streamCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return streamCollection.Count; }
        }

        public void Clear()
		{
			streamCollection.Clear();
        }

		public stream Remove(int index) 
		{ 
            stream obj = streamCollection[index];
            streamCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            streamCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(stream),ElementName="stream",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public streamCollection __streamCollection;
		
		[XmlIgnore]
		public streamCollection streamCollection
		{
			get
			{
				if (__streamCollection == null) __streamCollection = new streamCollection();
				return __streamCollection;
			}
			set {__streamCollection = value;}
		}

		public streams()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}


	[XmlType(TypeName="stream"),Serializable]
	public partial class stream
	{

		[XmlAttribute(AttributeName="id",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __id;
		
		[XmlIgnore]
		public string id
		{ 
			get { return __id; }
			set { __id = value; }
		}

		[XmlElement(ElementName="title",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __title;
		
		[XmlIgnore]
		public string title
		{ 
			get { return __title; }
			set { __title = value; }
		}

		[XmlElement(ElementName="price",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __price;
		
		[XmlIgnore]
		public string price
		{ 
			get { return __price; }
			set { __price = value; }
		}

		[XmlElement(ElementName="realprice",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __realprice;
		
		[XmlIgnore]
		public string realprice
		{ 
			get { return __realprice; }
			set { __realprice = value; }
		}

		[XmlElement(ElementName="date",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __date;
		
		[XmlIgnore]
		public string date
		{ 
			get { return __date; }
			set { __date = value; }
		}

		public stream()
		{
		}

		public void MakeSchemaCompliant()
		{
		}
	}
}
